module Kitbash
  module Bulk
    module SynonymBulk
      def sport_names
        @@sport_names ||= [
          "Trapeze",
          "Base jumping",
          "Rugby football",
          "Wingsuit flying",
          "Off-roading",
          "Hare coursing",
          "Kabaddi",
          "Supercross",
          "Canoeing",
          "Patball",
          "Mountain running",
          "Sledding",
          "Xare",
          "Samoa rules",
          "Noodling",
          "Foosball",
          "Bossaball",
          "Show jumping",
          "Street workout",
          "Disc golf (urban)",
          "Spearfishing",
          "Snorkelling",
          "Aerobatics",
          "Goalball",
          "Table tennis",
          "Campdrafting",
          "Wheelchair rugby league",
          "Futsal",
          "Rugby tens",
          "Hoop",
          "Road running",
          "Jorkyball",
          "Hearthstone",
          "Vale tudo",
          "Street hockey",
          "Popinjay",
          "Pradal serey",
          "Gatka",
          "Krabi–krabong",
          "Kitesurfing",
          "Palant",
          "Grand prix motorcycle racing",
          "Zen bu kan kempo",
          "Crossfit",
          "Bobsleigh",
          "Drag racing",
          "Dumog",
          "Kyūjutsu",
          "Mahjong",
          "Underwater hockey",
          "Indoor cricket",
          "Uppies and downies",
          "Squash tennis",
          "Four-ball",
          "Sword fighting",
          "Baton twirling",
          "Gouren",
          "Big game hunting",
          "Streetball",
          "Wrestling",
          "Flying trapeze",
          "Over",
          "Stihl timbersports series",
          "Camogie",
          "Subak",
          "Artistic cycling",
          "Pickleball",
          "Rodeo",
          "Big-game fishing",
          "Toboggan",
          "Tennis",
          "Cirit",
          "Touch rugby",
          "Butts up",
          "Moscow broomball",
          "Field archery",
          "Equitation",
          "Kyūdō",
          "Snow kiting",
          "Hapkido",
          "Gaelic football",
          "Cushion caroms",
          "Tent pegging",
          "Saddle bronc riding",
          "Calf roping",
          "10k run",
          "English pleasure",
          "Sambo",
          "Kite buggy",
          "Bodyboarding",
          "Segway polo",
          "Valencian frontó",
          "5k run",
          "Frontenis",
          "Road racing",
          "Field lacrosse",
          "Sports car racing",
          "Lancashire wrestling",
          "Dominoes",
          "Ice climbing",
          "Newcomb ball",
          "Supermoto",
          "Free running",
          "Platform tennis",
          "Sholo guti",
          "American handball",
          "White water rafting",
          "Sumo",
          "Beach volleyball",
          "Marathon",
          "Steeplechase",
          "Greek wrestling",
          "Austus",
          "Cowboy",
          "Surf kayaking",
          "Horse polo",
          "T'ai chi ch'uan",
          "Competitive dancing",
          "Fullbore target rifle",
          "Polo",
          "Ba game",
          "Underwater cycling",
          "Sikaran",
          "Skater hockey",
          "Camping",
          "Rally raid",
          "High bar",
          "Motocross",
          "British baseball",
          "Blackball",
          "Geocaching",
          "Underwater ice hockey",
          "Heptathlon",
          "Freestyle motocross",
          "Wakeboarding",
          "Jacquet",
          "Danish longball",
          "Charreada",
          "Snooker",
          "Greco-roman wrestling",
          "Wushu",
          "Hurdles",
          "Skateboarding",
          "Fishing",
          "Swamp football",
          "Chinlone",
          "Immersion finswimming",
          "Flutterguts",
          "Sailing",
          "Ski touring",
          "Korfball",
          "Land windsurfing",
          "Individual medley",
          "Six-red snooker",
          "Aerial silks",
          "Carom billiards",
          "Goat tying",
          "Pencak silat",
          "Papi fut",
          "Flight archery",
          "Rinkball",
          "Disc dog",
          "Racketball",
          "Track cycling",
          "Fistball",
          "Naginatajutsu",
          "Caid",
          "Oztag",
          "Paintball",
          "Offshore powerboat racing",
          "Metallic silhouette shooting",
          "Sprint",
          "Silat",
          "Juggling",
          "Jeet kune do",
          "Eskrima",
          "Diving",
          "Cornish hurling",
          "Duathlon",
          "Jogo do pau",
          "Powerbocking",
          "Clash royale",
          "One-pocket",
          "F1 powerboat racing",
          "Biribol",
          "American flag rugby",
          "Crossminton",
          "Jujutsu",
          "Snowboarding",
          "Board track racing",
          "Seven-ball",
          "Kenjutsu",
          "Trap shooting",
          "Fell running",
          "Kenpō",
          "Tag rugby",
          "Rc racing",
          "Speed golf",
          "Archery",
          "Frisian handball",
          "Bat and trap",
          "Formula racing",
          "Canoe polo",
          "Starcraft",
          "Freestyle",
          "Ten-ball",
          "Chicago",
          "Cheerleading",
          "Throwball",
          "Tt racing",
          "Water basketball",
          "Racquetball",
          "Sporting clays",
          "Mob football",
          "Jeu de paume",
          "Vintage racing",
          "Rogaining",
          "Bartitsu",
          "Powerlifting",
          "Medley relay",
          "Valencian pilota",
          "Taidō",
          "Hwa rang do",
          "Corkball",
          "Mancala",
          "Freestyle bmx",
          "Team roping",
          "Horseball",
          "Flyak",
          "Slacklining",
          "Bmx",
          "Yağlı güreş",
          "Draughts",
          "Eight-man football",
          "Eton fives",
          "Production car racing",
          "Jianzi",
          "Shurikenjutsu",
          "Ringette",
          "Drag boat racing",
          "Cycle speedway",
          "Freestyle swimming",
          "Backpacking",
          "Tumbling",
          "Paralympic football",
          "Parasailing",
          "Hot box",
          "Balkline and straight rail",
          "Underwater orienteering",
          "Keep away",
          "Stand up paddle boarding",
          "Pelota mixteca",
          "Practical shooting",
          "Basque traditional weightlifting",
          "Powerchair football",
          "Three-ball",
          "Target archery",
          "Sogo",
          "Banzai skydiving",
          "Bagatelle",
          "Kin-ball",
          "Kendo",
          "Battōjutsu",
          "Basketball",
          "Netball",
          "Indoor football",
          "Fencing",
          "Cockfighting",
          "Decathlon",
          "Stunt",
          "Ultimate frisbee",
          "Cutting",
          "Keepie uppie",
          "Surf fishing",
          "Skysurfing",
          "Artistic pool",
          "Hang gliding",
          "Amateur wrestling",
          "Rallycross",
          "Yubi lakpi",
          "Unicycle basketball",
          "Deep-water soloing",
          "Strength athletics",
          "Formula student",
          "Skimboarding",
          "Egyptian stick fencing",
          "Deer hunting",
          "Polocrosse",
          "Five-pins",
          "Skydiving",
          "Hillclimbing",
          "Sport climbing",
          "Collar-and-elbow",
          "Rallying",
          "Checkers",
          "Nguni stick-fighting",
          "English billiards",
          "Match play",
          "Traditional climbing",
          "Shōrin-ryū shidōkan",
          "Abseiling",
          "Scrabble",
          "Marching band",
          "Bushwhacking",
          "Aiki-jūjutsu",
          "Rossall hockey",
          "Track racing",
          "Model yacht racing",
          "Ice hockey",
          "Ribbon",
          "Nine-a-side footy",
          "Kickboxing",
          "Shogi",
          "Pentathlon",
          "Enduro",
          "Equestrian vaulting",
          "Metro footy",
          "Killer",
          "Slow pitch",
          "Bodybuilding",
          "Savate",
          "Golf",
          "Goaltimate",
          "Paramotoring",
          "Floor",
          "Indoor field hockey",
          "Water polo",
          "Trial",
          "Darts",
          "Letterboxing",
          "Ultramarathon",
          "Rope",
          "Kilikiti",
          "Superbike racing",
          "Arena football",
          "Brännboll",
          "Capture the flag",
          "Waymarking",
          "Ninjutsu",
          "Hunter",
          "Pond hockey",
          "Creeking",
          "Stické",
          "Freestyle wrestling",
          "Quidditch",
          "Sinuca brasileira",
          "Speed skiing",
          "Sledge hockey",
          "Speedball",
          "Freestyle football",
          "Gaelic handball",
          "Parachuting",
          "Mod league",
          "Bicycle",
          "Street football",
          "Eclipse ball",
          "Surfboat",
          "Wolf hunting",
          "Steer roping",
          "Reining",
          "Royal shrovetide football",
          "Shuai jiao",
          "Wall game",
          "Indoor netball",
          "Snow rugby",
          "Deaf basketball",
          "Gig racing",
          "Casting",
          "Calcio fiorentino",
          "Dancesport",
          "Xing yi quan",
          "Skins game",
          "Auto race",
          "Team penning",
          "Beach basketball",
          "Hardball squash",
          "Whitewater kayaking",
          "Fives",
          "Biathlon",
          "Arimaa",
          "Skiing",
          "Telemark skiing",
          "One day international",
          "Composite rules shinty-hurling",
          "Gridiron football",
          "Hunter-jumpers",
          "Straight pool",
          "Underwater rugby",
          "Lelo burti",
          "Three-cushion",
          "Autograss",
          "Varzesh-e pahlavani",
          "Bujinkan",
          "Speed pool",
          "Casterboarding",
          "Nine-man football",
          "Axe throwing",
          "Underwater football",
          "Bumper pool",
          "Kelly pool",
          "Chilean rodeo",
          "Wheelchair basketball",
          "Choi kwang-do",
          "Tetrathlon",
          "Iaidō",
          "Woodsman",
          "Kuk sool won",
          "Basque pelota",
          "Fujian white crane",
          "Floorball",
          "Disc golf",
          "British bulldogs",
          "Systema",
          "Endurance riding",
          "Figure skating",
          "Rocket league",
          "Cross-country rally",
          "Hydroplane racing",
          "Quizzing",
          "Field game",
          "Town ball",
          "Bouldering",
          "Cyclo-cross",
          "Still rings",
          "Judo",
          "Lethwei",
          "Pehlwani",
          "Coastal and ocean rowing",
          "Sport fishing",
          "Eight-ball",
          "Sport diving",
          "Jai alai",
          "Kayaking",
          "Artistic billiards",
          "Go-moku",
          "Ski jumping",
          "Kite landboarding",
          "Tractor pulling",
          "Parkour",
          "Diplomacy",
          "Rocball",
          "Harpastum",
          "Snowkiting",
          "Curling",
          "Rounders",
          "Surface finswimming",
          "Dirt track racing",
          "Bokator",
          "Team handball",
          "Adventure racing",
          "Chess960",
          "Broomball",
          "International rules football",
          "Riverboarding",
          "Unicycle trials",
          "Kalaripayattu",
          "Rafting",
          "Bottle pool",
          "Peteca",
          "Elle",
          "Ball badminton",
          "Touch football",
          "Uneven bars",
          "Acrobatic gymnastics",
          "Women's lacrosse",
          "Strike",
          "Slot car racing",
          "Land sailing",
          "Lapta",
          "Cutthroat",
          "Aquathlon",
          "Okinawan kobudō",
          "Stock car racing",
          "Horse racing",
          "Dota 2",
          "Iaijutsu",
          "Banger racing",
          "Miniten",
          "Neppis",
          "Water volleyball",
          "Jet sprint boat racing",
          "Cnapan",
          "Power hockey",
          "Artistic gymnastics",
          "Wallyball",
          "Go",
          "Wing chun",
          "American football",
          "Australian handball",
          "Boffer fighting",
          "Trail running",
          "Ga-ga",
          "Rugby league nines",
          "Club",
          "Cluster ballooning",
          "Three sided football",
          "Shootfighting",
          "Tennis polo",
          "Aerobic gymnastics",
          "Beagling",
          "Marine corps martial arts program",
          "La soule",
          "Single skating",
          "Kumdo",
          "Handball",
          "Bank pool",
          "Freediving",
          "Underwater photography",
          "Footbag net",
          "Waboba",
          "Sanshou",
          "Slamball",
          "Drifting",
          "Soft tennis",
          "Ice racing",
          "Wallball",
          "Scrub baseball",
          "Rink bandy",
          "Knattleikr",
          "Qianball",
          "Hunting",
          "Streetluge",
          "Snooker plus",
          "Synchronized swimming",
          "Trick shot competition",
          "Kho kho",
          "Box lacrosse",
          "Futebol de salão",
          "International fronton",
          "Truck racing",
          "Twenty20",
          "Pato",
          "Kiteboarding",
          "Racewalking",
          "Universal football",
          "Double disc court",
          "Speed-ball",
          "Unicycling",
          "Cornish wrestling",
          "Volata",
          "Footvolley",
          "Jūkendō",
          "Triathlon",
          "Rugby sevens",
          "Gymnastics",
          "Jugger",
          "Bullriding",
          "Bar billiards",
          "Downhill mountain biking",
          "Fly fishing",
          "Desert racing",
          "Longboarding",
          "Nordic combined",
          "Wireball",
          "Speedcubing",
          "Roller hockey",
          "Apnoea finswimming",
          "Taekwondo",
          "Race of champions",
          "Sipa",
          "Paragliding",
          "Backstroke",
          "Formula libre",
          "Cycling",
          "Ki-o-rahi",
          "Spongee",
          "Bo-taoshi",
          "Silambam",
          "Ice dancing",
          "Autocross",
          "Paleta frontón",
          "Mountain unicycling",
          "Supersport racing",
          "Pole climbing",
          "Endurance racing",
          "Short track motor racing",
          "Inline hockey",
          "Ssireum",
          "Pole bending",
          "Glima",
          "Kickball",
          "Monster truck",
          "Touring car racing",
          "Hide and seek",
          "Tchoukball",
          "Squash",
          "Baseball pocket billiards",
          "Canadian football",
          "High power rifle",
          "Icosathlon",
          "Walking",
          "Tang soo do",
          "Paralympic volleyball",
          "Racketlon",
          "Sandboarding",
          "Roping",
          "Grappling",
          "Ice fishing",
          "Tag",
          "Ice yachting",
          "Cestoball",
          "Hardcourt bike polo",
          "Brazilian jiu-jitsu",
          "Road bicycle racing",
          "Shinty",
          "Rope climbing",
          "Hana ichi monme",
          "Modern arnis",
          "Oina",
          "Bando",
          "Bifins",
          "Time attack",
          "Cribbage",
          "Super smash bros. melee",
          "Clay pigeon shooting",
          "Freeboating",
          "Five-a-side football",
          "Mongolian wrestling",
          "Unicycle hockey",
          "Windsurfing",
          "Pocket billiards",
          "Land speed records",
          "Chinese checkers",
          "Outrigger canoeing",
          "Kung fu",
          "Cricket",
          "Malla-yuddha",
          "Northern praying mantis",
          "Regularity rally",
          "Stickball",
          "Cross country",
          "Rugby league sevens",
          "Softball",
          "Tee ball",
          "Orienteering",
          "Wiffleball",
          "Boli khela",
          "Marn grook",
          "Cross-country running",
          "Luge",
          "Jittejutsu",
          "Competitive swimming",
          "Bareback bronc riding",
          "Barrel racing",
          "Freestyle skiing",
          "Snowmobile racing",
          "Sprint football",
          "Hopper ballooning",
          "Ladies' gaelic football",
          "Masters football",
          "Hojōjutsu",
          "Streetboarding",
          "Field hockey",
          "Mountaineering",
          "Novuss",
          "Ringball",
          "Snowshoe running",
          "Taekkyeon",
          "Nine-ball",
          "Reversi",
          "Pankration",
          "Catch wrestling",
          "Risk",
          "Eventing",
          "Flag football",
          "Dodge disc",
          "Cammag",
          "Limited overs cricket",
          "League of legends",
          "Static trapeze",
          "Freestyle footbag",
          "Legends car racing",
          "Sur-papakh",
          "Paddleboarding",
          "Beach tennis",
          "Cross-country skiing",
          "Shoot boxing",
          "Bandy",
          "Motorcycle speedway",
          "Fastnet",
          "Xiangqi",
          "Free-style moto",
          "Model aircraft racing",
          "Miniature golf",
          "Human powered aircraft",
          "Czech handball",
          "Folkrace",
          "Model aircraft",
          "Racquets",
          "Kite fighting",
          "Overwatch",
          "Rhythmic gymnastics",
          "Beach handball",
          "Episkyros",
          "Cliff diving",
          "Mini rugby",
          "Alpine skiing",
          "Vajra-mushti",
          "Sōjutsu",
          "Butterfly stroke",
          "Bowlliards",
          "Dragon boat racing",
          "Dodgeball",
          "Capoeira",
          "Rotation",
          "Mixed martial arts",
          "Skyrunning",
          "Mountainboarding",
          "Padel",
          "Modern pentathlon",
          "Sea kayaking",
          "Pesäpallo",
          "Sport stacking",
          "Professional wrestling",
          "Target shooting",
          "Air racing",
          "Rugby fives",
          "Rope jumping",
          "Climbing",
          "Chinese handball",
          "Skeleton",
          "Ekiden",
          "Sport kite",
          "Beach rugby",
          "Rowing",
          "Indoor soccer",
          "Ball hockey",
          "Single scull",
          "Gungdo",
          "Squirt boating",
          "Red rover",
          "Vovinam",
          "Kart racing",
          "Cowboy action shooting",
          "Krav maga",
          "Kick the can",
          "Parallel bars",
          "Pickup truck racing",
          "Eton wall game",
          "Kemari",
          "Powered hang glider",
          "Hockey",
          "Harness racing",
          "Stool ball",
          "Skeet shooting",
          "Squash 57",
          "Hiking",
          "Matkot",
          "Cross-country mountain biking",
          "Kajukenbo",
          "Barrel jumping",
          "Chess",
          "Dice stacking",
          "Trampolining",
          "Yukigassen",
          "Pair skating",
          "Indoor archery",
          "Balance beam",
          "Palla",
          "Street unicycling",
          "Nordic skiing",
          "Breaststroke",
          "Jōdō",
          "Beach soccer",
          "Baguazhang",
          "Lacrosse",
          "Kneeboarding",
          "Pool",
          "Hurling",
          "Buzkashi",
          "All-terrain vehicle competition",
          "Model aerobatics",
          "Schwingen",
          "Badminton",
          "The massachusetts game",
          "Guts",
          "Stratego",
          "Mud bogging",
          "Muay thai",
          "Urban golf",
          "Test cricket",
          "Rec footy",
          "Harrow football",
          "Folk wrestling",
          "Frisbee",
          "Gliding",
          "Rock climbing",
          "Torball",
          "Off-road racing",
          "Debating",
          "Robot combat",
          "Half marathon",
          "Steinstossen",
          "Old cat",
          "Four square",
          "Coasteering",
          "Vigoro",
          "Midget car racing",
          "Six-man football",
          "Ball",
          "Real tennis",
          "Football tennis",
          "Metallic silhouette",
          "Hooverball",
          "Skibobbing",
          "Boxing",
          "Cuju",
          "Shorinji kempo",
          "Volleyball",
          "Cowboy polo",
          "Wheelstand competition",
          "Demolition derby",
          "Surfing",
          "Breakaway roping",
          "Hornussen",
          "Dirt jumping",
          "Steer wrestling",
          "Ice speedway",
          "Ultralight aviation",
          "Powered paragliding",
          "Miniature bull riding",
          "Yak polo",
          "Fox hunting",
          "Russian pyramid",
          "Dinghy sailing",
          "Baseball",
          "Highland games",
          "Punchball",
          "Aid climbing",
          "Cycle polo",
          "Shaolin kung fu",
          "Intercrosse",
          "Football",
          "Olympic weightlifting",
          "Hunger games",
          "Street racing",
          "Kurash",
          "Angling",
          "Karate",
          "Dressage",
          "Sprint car racing",
          "Benchrest shooting",
          "Underwater target shooting",
          "Airsoft",
          "Rock fishing",
          "Field handball",
          "Jousting",
          "Vault",
          "Personal water craft",
          "Wakesurfing",
          "Australian football",
          "Scuba diving",
          "Motorcycle drag racing",
          "Woggabaliri",
          "Mixed climbing",
          "Sudoku",
          "Haxey hood",
          "Scootering",
          "Backgammon",
          "Shidōkan karate",
          "Bronc riding",
          "Canyoning",
          "Matball",
          "Gymkhana",
          "Indoor enduro",
          "Pommel horse",
          "Freeboard",
          "Elephant polo",
          "Field target",
          "Card stacking",
          "Rugby league",
          "Superside",
          "Sepak takraw",
          "Tower running",
          "Bicycle polo",
          "Laser tag",
          "Aikido",
          "Skijoring",
          "Grasstrack",
        ]
      end


      def software_names
        @@software_names ||= [
          "Visual J#",
          "Objective-C",
          "AMOS",
          "ALGOL",
          "FreeBASIC",
          "Microsoft Small Basic",
          "XPL",
          "PyScripter",
          "Zeno",
          "Ghost OS",
          "OCaml",
          "Zsh",
          "A#",
          "J#",
          "Komodo Edit",
          "KDevelop",
          "NetBSD",
          "Amiga Unix",
          "HLSL",
          "LibreOffice",
          "Visual Studio",
          "PocketStudio",
          "AMSDOS",
          "SCO Unix",
          "Assembly Language",
          "MicroEMACS",
          "JavaFX Script",
          "Zorin OS",
          "Clojure",
          "Windows CE",
          "Logo",
          "Legoscript",
          "Mesa",
          "D",
          "Machine code",
          "PhpED Professional",
          "DOS",
          "Linux",
          "BCPL",
          "illumos",
          "LPC",
          "Windows",
          "SML",
          "Stada",
          "JBuilder",
          "Plan 9 from Bell Labs",
          "TextEdit",
          "PyCharm",
          "Notepad",
          "JScript",
          "Visual Basic",
          "RStudio",
          "AIX",
          "XBase++",
          "NeXTSTEP",
          "Javascript",
          "Visual FoxPro",
          "Code::Blocks",
          "EXEC II",
          "Atom",
          "TXL",
          "Vi",
          "MOS",
          "MATLAB",
          "CLion",
          "CP/CMS",
          "Apple SOS",
          "Ada",
          "Remix OS",
          "nvi",
          "Java",
          "Lua",
          "GNU",
          "CodeLite",
          "Nano",
          "C*",
          "BPEL",
          "Bash",
          "Ruby",
          "Xcode",
          "PHPEdit",
          "PEARL",
          "Erlang",
          "AppCode",
          "Lisp",
          "Dart",
          "Microsoft Visual Studio",
          "Darwin",
          "Excel",
          "MUMPS",
          "NoteTAb",
          "Netbeans",
          "MyEclipse",
          "Curl",
          "C Shell",
          "MonoDevelop",
          "SlickEdit",
          "Windows NT",
          "MIPS",
          "WebAssembly",
          "AmigaOS",
          "ed",
          "R++",
          "Nim",
          "X10",
          "Mousepad",
          "MS-DOS",
          "jEdit",
          "XTS-400",
          "Rust",
          "ECMAScript",
          "Vim script",
          "Nodeclipse",
          "C#",
          "Word",
          "Oak",
          "MDL",
          "Dev-Pascal",
          "J++",
          "Qt Creator",
          "Notepad2",
          "Ceylon",
          "QtScript",
          "FORTRAN",
          "OS/8",
          "XBase",
          "Visual Studio Code",
          "Inform",
          "OpenBSD",
          "Apple Pascal",
          "Goobuntu",
          "Chromium OS",
          "Simula",
          "Gnome",
          "IntelliJ",
          "Unix shell",
          "Krita",
          "APL",
          "EiffelStudio",
          "LispWorks",
          "Tcl",
          "FreeDOS",
          "OSv",
          "LISA",
          "SQL",
          "UnixWare",
          "C",
          "Ubuntu",
          "Kotlin",
          "R",
          "Swift",
          "Go",
          "Visual Fortran",
          "C--",
          "OS/2 Warp",
          "BASIC",
          "ColdFusion",
          "X11 Xedit",
          "Pico",
          "XSharp",
          "eC",
          "NetWare",
          "Perl 6",
          "Wolfram Language",
          "X++",
          "EXEC I",
          "Haxe",
          "Codeanywhere",
          "BeOS",
          "PLEX",
          "Unix",
          "TextMate",
          "SymbOS",
          "Cg",
          "COBOL",
          "XPath",
          "CoffeeScript",
          "PikeOS",
          "Dreamweaver",
          "RISC OS",
          "GPL",
          "Gedit",
          "Microcode",
          "Mac OS",
          "CP/M",
          "PHPEclipse",
          "F",
          "Octave",
          "TextPad",
          "NetBeans",
          "DOS/360",
          "JDeveloper",
          "Neko",
          "dBasic",
          "Object Lisp",
          "Haskell",
          "KDE",
          "LiveCode",
          "ZetaLisp",
          "Object Pascal",
          "HDOS",
          "VS/9",
          "Python",
          "Amiga E",
          "RubyMine",
          "OS/360",
          "Notepad++",
          "J",
          "MicroScript",
          "ARX",
          "ProDOX",
          "Delphi",
          "Leafpad",
          "BBEdit",
          "Z80-RIO",
          "Julia",
          "SLIME",
          "RPG",
          "Emacs",
          "TeX",
          "Android",
          "Solaris",
          "CDOS",
          "TeXShop",
          "RDOS",
          "TypeScript",
          "Komodo IDE",
          "Visual Basic .NET",
          "LynxOS",
          "Caml",
          "Free Pascal IDE",
          "Midori",
          "OS/2",
          "OpenSolaris",
          "NPL",
          "GLD",
          "Perl",
          "BSD",
          "Sublime Text",
          "KWrite",
          "C++",
          "Apple DOX",
          "Eclipse",
          "Mathematica",
          "Geany",
          "Atari DOS",
          "Objective-J",
          "Vim",
          "Xenix",
          "iOS",
          "JCreator",
          "EGL",
          "AOS",
          "Pascal",
          "Racket",
          "Visual LISP",
          "Picolisp",
          "CMS-2",
          "Emacs Lisp",
          "YAML",
          "Trac",
          "CPL",
          "F#",
          "AutoLisp",
          "DrRacket",
          "XEDIT",
          "IDLE",
          "ReactOS",
          "GDScript",
          "LaTeX",
          "LotusScript",
          "OpenCL",
          "PHP",
          "OBJ2",
          "Smalltalk",
          "Visual J++",
        ]
      end


      def study_name
        @@study_name ||= [
          "Parallel algorithms",
          "Landscape design",
          "Analytical chemistry",
          "Hydrodynamics",
          "Linear programming",
          "Psychotherapy",
          "Artillery",
          "Philosophy of mathematics",
          "Atmospheric chemistry",
          "Political history",
          "Positive psychology",
          "Philosophy of music",
          "Community psychology",
          "Forensic pathology",
          "Figurational sociology",
          "Quality control",
          "Confucianism",
          "Sociology of immigration",
          "Linnaean taxonomy",
          "Occupational therapy",
          "Real estate economics",
          "Moral psychology and descriptive ethics",
          "American politics",
          "Social theory",
          "Virtue ethics",
          "Marxist sociology",
          "Ethnobotany",
          "Educational psychology",
          "Behavioural science",
          "Semiotics",
          "Programming paradigms",
          "Ceramic engineering",
          "Queer studies",
          "Military engineering",
          "Post-colonial literature",
          "Sociology of sport",
          "Drawing",
          "Physics education",
          "Theoretical sociology",
          "Geodesy",
          "Nationalism studies",
          "Steganography",
          "American history",
          "Science policy",
          "Radio astronomy",
          "Empirical sociology",
          "Hydrology",
          "International economics",
          "Appetite",
          "Formal methods",
          "Coastal geography",
          "Philosophy of education",
          "Critical theory",
          "Investment policy",
          "Nuclear physics",
          "Food pairing",
          "Solid-state chemistry",
          "Political culture",
          "Group psychology",
          "Domestic policy",
          "Assignment problem",
          "Lti system theory",
          "Mathematical psychology",
          "Advertising",
          "Sociology of marriage",
          "Political geography & geopolitics",
          "Materials engineering",
          "Policy studies",
          "Sociology of human consciousness",
          "Sociological theory",
          "Dramaturgy",
          "Constitutional law",
          "Vehicle engineering",
          "Health informatics",
          "Edaphology",
          "Topos theory",
          "Inorganic chemistry",
          "Logistics",
          "Aerospace engineering",
          "Screenwriting",
          "Fire safety",
          "Public economics",
          "Electronic engineering",
          "Ethnomusicology",
          "Arms control",
          "Social policy",
          "Command and control",
          "Heterosexism",
          "Prehistoric archaeology",
          "Civil law",
          "Urology",
          "Ancient",
          "Consumer psychology",
          "Doctrine",
          "European history",
          "Statistical mechanics",
          "Resource economics",
          "Physical geography",
          "Theism and atheism",
          "Meteorology",
          "Ethnozoology",
          "Cosmology",
          "Ergonomics",
          "Chinese folk religion",
          "Sociotechnical systems theory",
          "Music therapy",
          "Philosophical logic",
          "New testament greek",
          "Medical psychology",
          "Admiralty law",
          "Veterinary medicine",
          "Islamic law",
          "System dynamics",
          "Drug policy reform",
          "Sociology of film",
          "Competition law",
          "Mechatronics",
          "Vehicles",
          "Mercenary",
          "Biochemical systems theory",
          "Sociology of conflict",
          "Policy analysis",
          "Astrophysics",
          "Supranational law",
          "Mathematics education",
          "Data management",
          "Analytic number theory",
          "Cell biology",
          "Media studies",
          "Phytochemistry",
          "Disaster response",
          "Ethnography",
          "Astrobiology",
          "Missiology",
          "Affine geometry",
          "Demography",
          "Ancient philosophy",
          "Psychology of religion",
          "Econometrics",
          "Discourse analysis",
          "Victimology",
          "Futures studies",
          "Organizational psychology",
          "Japanology",
          "Sociology of space",
          "Human services",
          "Mathematical optimization",
          "Physical chemistry",
          "Biocybernetics",
          "Corporations",
          "Number theory",
          "Ophthalmology",
          "Dramaturgical sociology",
          "Infographics",
          "Church history",
          "Macroeconomics",
          "Cryptography",
          "Mineralogy",
          "Infrastructure",
          "Principles of war",
          "Environmental policy",
          "Block design and analysis of variance",
          "Conspiracy theory",
          "Distributed algorithms",
          "Critical pedagogy",
          "Astronautics",
          "Information economics",
          "Palaeoclimatology",
          "Central asian studies",
          "Endodontics",
          "Physical therapy",
          "Set theory",
          "Toy and amusement design",
          "Pragmatics",
          "Numerical analysis",
          "Conducting",
          "Geochemistry",
          "Computability theory",
          "Fluid dynamics",
          "Grammar",
          "Optics",
          "Educational leadership",
          "Programming languages",
          "Geography",
          "Infrared astronomy",
          "Comparative law",
          "Cytogenetics",
          "Military education",
          "Behavioural genetics",
          "Philology",
          "Information systems",
          "Goal",
          "Business analysis",
          "Vocational education",
          "Fire ecology",
          "Information system",
          "Tort law",
          "Musicology",
          "Seafaring",
          "Business informatics",
          "Galaxy formation and evolution",
          "Elementary education",
          "Endocrinology",
          "Mass transfer",
          "Computer vision",
          "Scriptural study and languages",
          "Cryogenics",
          "Myrmecology",
          "Algebra",
          "Remote sensing",
          "Horticulture",
          "New media journalism",
          "Celtic studies",
          "Computer communications",
          "War crimes",
          "War",
          "Mysticism",
          "Biomolecular engineering",
          "Systems neuroscience",
          "Philosophy of mind",
          "Human–computer interaction",
          "Administrative law",
          "Human geography",
          "Space policy",
          "Sociology of education",
          "Development economics",
          "Magnetohydrodynamics",
          "Emergency medicine",
          "Tax policy",
          "Pastoral theology",
          "Social choice theory",
          "Microsociology",
          "Conflict theory",
          "History of literature",
          "Humanistic psychology",
          "Collective bargaining",
          "Finance",
          "Cyberwarfare",
          "Molecular virology",
          "Radio",
          "Chinese history",
          "Climatology",
          "Religious war",
          "Fine arts",
          "Regression",
          "Meta-philosophy",
          "Labor law",
          "Psychobiology",
          "Educational sociology",
          "Justification",
          "Dental surgery",
          "E-business",
          "History of computer science",
          "Operations management",
          "Logic",
          "Sociology of development",
          "Literary criticism",
          "Animal rights",
          "Early modern",
          "Military sports",
          "Chronobiology",
          "Amphibious warfare",
          "Reliability theory",
          "Woodcraft",
          "Bioeconomics",
          "Elementary particle physics",
          "Respiratory medicine",
          "Welfare economics",
          "Landscape architecture",
          "Philosophy of physics",
          "Social conflict theory",
          "Total war",
          "Animal communications",
          "Gamma ray astronomy",
          "Evolutionary sociology",
          "Stellar astrophysics",
          "Electromagnetism",
          "Digital media",
          "Sexology",
          "Optimal maintenance",
          "Film",
          "Music education",
          "Physical cosmology",
          "Psychoanalytic sociology",
          "Fourier analysis",
          "Etymology",
          "Hematology",
          "Supply chain management",
          "Continuum mechanics",
          "Leisure studies",
          "Architectural sociology",
          "Sociology of deviance",
          "Ichthyology",
          "Sample survey",
          "Human ecology",
          "Sociology of music",
          "Category theory",
          "Surgical strike",
          "Cleaning",
          "Knowledge management",
          "Photography",
          "Woodwinds, brass, and percussion",
          "Natural resource management",
          "Strategy",
          "Electrical engineering",
          "Stage design",
          "Behavioral geography",
          "Mass transit",
          "Hematopathology",
          "Purification",
          "Cryptanalysis",
          "Environmental communication",
          "Topology",
          "Nematology",
          "Social research",
          "Procedural law",
          "Polish sociology",
          "Information science",
          "Physiotherapy",
          "Animation",
          "Orthoptics",
          "Theoretical physics",
          "Mental health",
          "Expert systems",
          "Planktology",
          "Experimental economics",
          "Community organizing",
          "Automotive engineering",
          "Phonetics",
          "Translation",
          "Differential topology",
          "Geriatrics",
          "Cheminformatics",
          "High-performance computing",
          "Economic value",
          "Molecular engineering",
          "Pakistan studies",
          "User interface design",
          "Transpersonal psychology",
          "Infantry",
          "Sikhism",
          "Counter-intelligence",
          "Parallel computing",
          "Sociology of emotions",
          "Complex systems",
          "Astrophysical plasma",
          "Demography/population",
          "Programming language semantics",
          "Population genetics",
          "Structural mechanics",
          "Histology",
          "American literature",
          "New cybernetics",
          "Evolutionary psychology",
          "Intelligence agency",
          "Marketing",
          "Operator theory",
          "Indology",
          "Moral theology",
          "Coastal engineering",
          "Mathematical sociology",
          "Synchronic linguistics",
          "Computational neuroscience",
          "History of philosophy",
          "Sociology of generations",
          "Puppetry",
          "Meta-ethics",
          "Sacred music",
          "Computer graphics",
          "Nuclear energy policy",
          "Synthetic chemistry",
          "Higher education",
          "Platonism",
          "Continental philosophy",
          "Tourism geography",
          "Earthquake engineering",
          "Alternative education",
          "African history",
          "Biochemical engineering",
          "Physiology",
          "Libertarianism",
          "Naval architecture",
          "Deception",
          "Clinical physiology",
          "Islamic studies",
          "Scoutcraft",
          "Paleobiology",
          "Pharmaceutical sciences",
          "Business economics",
          "Sociology of language",
          "Special operations",
          "Applied philosophy",
          "Plasma physics",
          "Choral conducting",
          "Filmmaking",
          "Ethnomethodology",
          "Animal husbandry",
          "Gender studies",
          "Therapy",
          "Nutrition",
          "Agricultural economics",
          "Ancient greek history",
          "Asian studies",
          "Military psychology",
          "Sociology of social change",
          "Computer architecture",
          "Linguistic typology",
          "Culturology",
          "Neuroscience",
          "Canadian politics",
          "Financial economics",
          "Control engineering",
          "Sindhology",
          "Battle",
          "Jealousy sociology",
          "Ordinary differential equations",
          "Informatics",
          "Strategic geography",
          "Business law",
          "Dynamic programming",
          "Islamic economics",
          "Physical education",
          "Apiology",
          "Vedic study",
          "Sport management",
          "Recreation ecology",
          "Contract law",
          "Zoroastrianism",
          "Specialty foods",
          "Economic sociology",
          "Mathematical statistics",
          "Sociology of organizations",
          "Educational philosophy",
          "Family law",
          "Algebraic geometry",
          "Communication studies",
          "Computational fluid dynamics",
          "Tectonics",
          "Industrial sociology",
          "Legal psychology",
          "Marxism",
          "Syntax",
          "Haemostasiology",
          "Anthropological linguistics",
          "Pharmacology",
          "Literary theory",
          "Applied psychology",
          "Cetology",
          "Gender theory",
          "Ethnolinguistics",
          "Law enforcement",
          "Emergency services",
          "Human evolution",
          "Chemical engineering",
          "Decontamination",
          "Teratology",
          "Quantum computing",
          "Phenomenology",
          "Epistemology",
          "Atomic physics",
          "Ethnoecology",
          "Toxicology",
          "Photochemistry",
          "Classical archaeology",
          "Cardiac electrophysiology",
          "Armor",
          "Public international law",
          "Propaganda",
          "Sculpture",
          "Finite element analysis",
          "Social psychology",
          "Organizational studies",
          "Sociology of food",
          "Chondogyo",
          "Complex system",
          "Crystallography",
          "Group theory",
          "Developmental biology",
          "Photonics",
          "Agronomy",
          "Defense industry",
          "Naval tactics",
          "Philosophy of perception",
          "Trauma surgery",
          "Early childhood education",
          "Phycology",
          "World-systems theory",
          "Sociology of technology",
          "Australian history",
          "Radiology",
          "Philosophy of economics",
          "Engineering physics",
          "Orchestral studies",
          "Public health",
          "Solid state physics",
          "Environmental chemistry",
          "Complexity economics",
          "Humanistic informatics",
          "Marine chemistry",
          "Intellectual history",
          "Morale",
          "Molecular biology",
          "Historical linguistics",
          "Cross-cultural studies",
          "Newtonian dynamics",
          "Sociology of religion",
          "Clinical psychology",
          "Oceanography",
          "Harmonic analysis",
          "Economic development",
          "Virology",
          "Occupational psychology",
          "Manufacturing engineering",
          "Normative ethics",
          "Gene-culture coevolution",
          "Quantum chemistry",
          "Poetry",
          "Escapology",
          "Quantitative psychology",
          "Forensic entomology",
          "Black holes",
          "Religious education",
          "Feminist geography",
          "Public safety",
          "Collateral damage",
          "Environmental management",
          "Geotechnical engineering",
          "Children's geographies",
          "Sound and music computing",
          "Affective science",
          "Citation analysis",
          "Dance notation",
          "Parasitology",
          "Counter-insurgency",
          "Nonprofit administration",
          "Systems theory",
          "Naval",
          "Language policy",
          "Batoning",
          "Pre-columbian era",
          "Control systems engineering",
          "Control theory",
          "Decision theory",
          "Private defense agency",
          "Food safety",
          "Public policy by country",
          "Scheduling",
          "Theatre",
          "Philosophy of religion",
          "English studies",
          "P-adic analysis",
          "Modern language",
          "Theater (warfare)",
          "Humanistic sociology",
          "New religious movements",
          "Second-order cybernetics",
          "Attrition",
          "Environmental science",
          "Technological history",
          "Femtochemistry",
          "Glaciology",
          "Green economics",
          "Sampling theory",
          "Private military company",
          "Experimental physics",
          "Intermodal transportation studies",
          "Business ethics",
          "Concurrency theory",
          "Neuroethology",
          "Musical composition",
          "Gravitational astronomy",
          "Non-fiction writing",
          "Anthropological criminology",
          "Travel psychology",
          "Mathematical system theory",
          "Child welfare",
          "Staff",
          "Physical metallurgy",
          "Usage",
          "Culinary tourism",
          "Tenrikyo",
          "Surgical pathology",
          "Purchasing",
          "Naval science",
          "Philosophy of history",
          "Paleontology",
          "Film studies",
          "Indigenous psychology",
          "Uv astronomy",
          "Optical astronomy",
          "Real analysis",
          "Linear algebra",
          "Ontology",
          "Civics",
          "Phenomenological sociology",
          "Technical drawing",
          "Feminine psychology",
          "Intelligence",
          "Neuroeconomics",
          "Word usage",
          "Human anatomy",
          "Algebraic topology",
          "Computational finance",
          "Probability",
          "Social economy",
          "Comparative literature",
          "Economic",
          "Wind ensemble conducting",
          "General practice",
          "Standard english",
          "Time geography",
          "Medical education",
          "Music genre",
          "Data structures",
          "Earth systems engineering and management",
          "Economic systems",
          "Multivariate analysis",
          "Sociology of terrorism",
          "Engineering cybernetics",
          "Obstetrics",
          "String theory",
          "Military operation",
          "Computational economics",
          "Acting",
          "Embryology",
          "Computer program",
          "Human biology",
          "Live action",
          "Animal law",
          "Computational chemistry",
          "Model theory",
          "Jewish law",
          "Military history",
          "Public speaking",
          "Women's studies",
          "Human development theory",
          "Counter-terrorism",
          "Modern history",
          "Soil science",
          "European studies",
          "Osteopathy",
          "Catalysis",
          "Ethics",
          "Energy policy",
          "Military simulation",
          "Special forces",
          "Speech communication",
          "Dietetics",
          "Composition studies",
          "Bushcraft",
          "Statistical theory",
          "Cytohematology",
          "Entomology",
          "Canadian studies",
          "Egyptology",
          "Organizational behavior",
          "Knowledge economy",
          "Microbiology",
          "Internet",
          "Flow chemistry",
          "Theft",
          "Korean studies",
          "Sociology of disaster",
          "Aquaculture",
          "Medical sociology",
          "Systematic theology",
          "Universal algebra",
          "Iranian history",
          "Hinduism",
          "Gastronomy",
          "Behavioral sociology",
          "Public policy school",
          "Christianity",
          "Christian theology",
          "Old church slavonic",
          "Parapsychology",
          "Natural language processing",
          "Modern philosophy",
          "Biomedical engineering",
          "Marine engineering",
          "Management",
          "Historical sociology",
          "Environmental sociology",
          "Computational statistics",
          "Biostatistics",
          "Security",
          "Chemistry education",
          "Sociomusicology",
          "Neuropsychology",
          "Christian ethics",
          "Decision analysis",
          "Digital asset",
          "Food porn",
          "Scientific visualization",
          "Transport economics",
          "Beekeeping",
          "Urban studies or urban sociology/rural sociology",
          "Partial differential equations",
          "Economic history",
          "Conservation biology",
          "Economic sector",
          "Wildlife management",
          "Cultural anthropology",
          "Counter-offensive",
          "Criminal procedure",
          "Semantics",
          "Nonverbal communication",
          "Mechanical engineering",
          "Astrochemistry",
          "Military science",
          "Materials science and engineering",
          "Forensic developmental psychology",
          "Political psychology",
          "Developmental systems theory",
          "Macrosociology",
          "Fluid mechanics",
          "Bioethics",
          "Accounting scholarship",
          "Multi-valued logic",
          "Systems biology",
          "Ecological psychology",
          "Traditional food",
          "Molecular mechanics",
          "Cosmochemistry",
          "Educational technology",
          "Distance education",
          "Forensic anthropology",
          "Social development",
          "Symbolic interactionism",
          "Analytical sociology",
          "Forensic psychology",
          "Sociology of culture",
          "Jazz studies",
          "Sociology of race and ethnic relations",
          "Image processing",
          "Asymmetric warfare",
          "Philosophy of engineering",
          "Consumer education",
          "Food policy",
          "Surgery",
          "Tactical objective",
          "Housing policy",
          "Agricultural education",
          "Cultural sociology",
          "Functional analysis",
          "Simulation",
          "Military intelligence",
          "International trade",
          "Nursing education",
          "Anatomical pathology",
          "Nanomaterials",
          "Common law",
          "Inventory theory",
          "Sociology of the internet",
          "Sociology of natural resources",
          "Medicinal chemistry",
          "Sociology of finance",
          "Accompanying",
          "Hermeneutics",
          "Program semantics",
          "Federal law",
          "Magazine",
          "Order theory",
          "Family systems theory",
          "Commutative algebra",
          "Systems theory in anthropology",
          "Legal management",
          "Systematic musicology",
          "Technology and equipment",
          "Infiltration",
          "Technology policy",
          "Development geography",
          "Graphic design",
          "Singing",
          "Surface chemistry",
          "Structural equation model",
          "Ecological engineering",
          "Television",
          "Ecology",
          "Assassination",
          "Biotechnology",
          "Systems science",
          "Piano",
          "Ergodic theory",
          "Histochemistry",
          "Critical sociology",
          "Early music",
          "Appalachian studies",
          "Mechanochemistry",
          "Environmental psychology",
          "East asian studies",
          "Computational physics",
          "Philosophy of chemistry",
          "Science and technology studies",
          "Delicacy",
          "Chemical",
          "Labor history",
          "Immunochemistry",
          "Dentistry",
          "Construction",
          "Corrections",
          "Functional programming",
          "Sociocybernetics",
          "Disaster research",
          "Biomaterials",
          "Mathematical physics",
          "Undercover",
          "Approximation theory",
          "Outline of video games",
          "Paramilitary",
          "Industrial policy",
          "Proxy war",
          "Engineering geology",
          "Critical management studies",
          "History of linguistics",
          "Computational sociology",
          "Naval engineering",
          "Sociology of punishment",
          "Geopolitics (political geography)",
          "Comparative education",
          "Nephrology",
          "Philosophy of space and time",
          "Economics",
          "Drug policy",
          "Digital journalism",
          "Zoology",
          "Living systems theory",
          "Intercultural communication",
          "Surveying",
          "Oral and maxillofacial surgery",
          "Recording",
          "Management cybernetics",
          "Civil engineering",
          "Cooking",
          "Environmental law",
          "Cognitive science",
          "Electrochemistry",
          "Ubiquitous computing",
          "Artificial neural network",
          "Sports coaching",
          "Incomes policy",
          "Hydraulic engineering",
          "Time series",
          "Computer security and reliability",
          "Information management",
          "Problem solving",
          "Collective behavior",
          "Medical toxicology",
          "Criminal justice",
          "Ancient egyptian religion",
          "Political economy",
          "Latin american history",
          "Relational database",
          "Biblical hebrew",
          "Canon law",
          "Arachnology",
          "Psychometrics",
          "Sinology",
          "Stellar evolution",
          "Public administration",
          "Covert operation",
          "Paleoecology",
          "Entrepreneurial economics",
          "Architecture",
          "Sociology of scientific knowledge",
          "Stem cell research policy",
          "Guerrilla warfare",
          "Gourmet",
          "Biological systems engineering",
          "Field theory",
          "Sociobiology",
          "Cavalry",
          "Southeast asian studies",
          "Decision science",
          "Deontic logic",
          "Graph theory",
          "Engineers",
          "Ecological economics",
          "Algebraic (symbolic) computation",
          "Museum administration",
          "Psychosomatic",
          "Public policy",
          "Ancient history",
          "Speech and language pathology",
          "Architectural engineering",
          "Astronomy",
          "Sacramental theology",
          "Architectural analytics",
          "Fractal geometry",
          "Biogeography",
          "Sociology of the history of science",
          "Cultural policy",
          "Evolutionary economics",
          "Recursion theory",
          "Craft",
          "Internal medicine",
          "Experimental psychology",
          "Systems ecology",
          "Commercial policy",
          "I-kuan tao",
          "Helioseismology",
          "Taxonomy",
          "Applied ethics",
          "Sports journalism",
          "Implantology",
          "Internet sociology",
          "Languages",
          "Traditional medicine",
          "Land management",
          "Non-standard analysis",
          "Sociology of gender",
          "Print journalism",
          "Societal of autism",
          "Systems philosophy",
          "Logic programming",
          "Conceptual systems",
          "Plastic surgery",
          "Urban planning",
          "Law and economics",
          "Wildlife observation",
          "Directing",
          "Clinical biochemistry",
          "Statistical modelling",
          "Information architecture",
          "Enterprise systems engineering",
          "Organology",
          "Operations research",
          "Population geography",
          "Financial econometrics",
          "Middle east studies",
          "Pomology",
          "Monetary policy",
          "Analysis",
          "Applied economics",
          "Cultural psychology",
          "Nontheism",
          "Chinese sociology",
          "Ranks",
          "Classics",
          "Mastery learning",
          "Theory of computation",
          "Tax law",
          "Sleep medicine",
          "Periodontics",
          "Entrepreneurship",
          "Social transformation",
          "Foodservice management",
          "Culinary arts",
          "Defensive",
          "Human behavioral ecology",
          "Pediatrics",
          "Cognitive psychology",
          "Imperative programming",
          "Formal verification",
          "Theology",
          "Cryobiology",
          "Medical social work",
          "Star formation",
          "Transportation engineering",
          "Emergency management",
          "Military law",
          "Music",
          "Applied sociology",
          "Algebraic number theory",
          "Foreign policy",
          "International organizations",
          "Charge",
          "Latin",
          "Shinto",
          "Jurisprudence",
          "Textile design",
          "Sex education",
          "Environmental ethics",
          "Homiletics",
          "Computational linguistics",
          "Ocean engineering",
          "Performance science",
          "Science studies",
          "Automated reasoning",
          "Medieval literature",
          "Black studies",
          "Diachronic linguistics",
          "Mathematical economics",
          "Feminist sociology",
          "Organic chemistry",
          "Scenography",
          "Aerial",
          "Sociology of the family",
          "Aerobiology",
          "Irregular warfare",
          "Ethnochoreology",
          "Geomorphology",
          "Organizational communication",
          "Differential psychology",
          "Pure sociology",
          "Viticulture",
          "Civil service",
          "Sociology of globalization",
          "Queer theory",
          "Geometry",
          "Biblical studies",
          "Civil procedure",
          "Physical fitness",
          "Instrumentation engineering",
          "Pedology",
          "History of dance",
          "Multimedia, hypermedia",
          "Molecular pathology",
          "Agricultural engineering",
          "Polymer engineering",
          "Hydrogenation",
          "Medieval philosophy",
          "Geography and outline of geography",
          "Interactionism",
          "Rehabilitation psychology",
          "Atheism",
          "Esotericism",
          "Film theory",
          "Conservation science",
          "Structural biology",
          "Theoretical chemistry",
          "Knowledge policy",
          "Sociology of peace, war, and social conflict",
          "Natural product chemistry",
          "Oomoto",
          "Pediatric psychology",
          "Mycology",
          "Hindu ethics",
          "Counter-attack",
          "Network science",
          "Project management",
          "Bioinformatics",
          "Food science",
          "General systems theory",
          "Nuclear engineering",
          "Distributed database",
          "Agnosticism",
          "Phonology",
          "Indian history",
          "Wireless computing",
          "Psephology",
          "Management information systems",
          "Ancient roman history",
          "Green chemistry",
          "Biological",
          "Foxhole",
          "Ethnohistory",
          "Information theory",
          "Orthodontics",
          "Sociology of literature",
          "Anthropology of religion",
          "Otolaryngology",
          "Structural sociology",
          "Trench warfare",
          "Biological anthropology",
          "Police science",
          "Xenobiology",
          "Ethnic studies",
          "Information",
          "Petrology",
          "Mock combat",
          "Affect control theory",
          "Network-centric warfare",
          "Hydrogeology",
          "Zoosemiotics",
          "Sociology of art",
          "Applied physics",
          "Psychiatry",
          "Feminist philosophy",
          "Gerontology",
          "Interaction design",
          "Military policy",
          "Mass communication",
          "Fourth-generation warfare",
          "Education policy",
          "Public service",
          "Social phenomenon",
          "Heat transfer",
          "Food studies",
          "Limnology",
          "Labor economics",
          "Sociology of science",
          "Music psychology",
          "Limited war",
          "Cover",
          "Philosophy of biology",
          "Database",
          "World englishes",
          "Film criticism",
          "Helminthology",
          "Landscape ecology",
          "Ecological systems theory",
          "Pulmonology",
          "Noncommutative geometry",
          "Pest control",
          "Maritime archaeology",
          "Philosophy of psychology",
          "Computational geometry",
          "Mythology and folklore",
          "Support vector machine",
          "Education and training",
          "Musical theatre",
          "Kinesiology",
          "Sociology of cyberspace",
          "Science education",
          "Daoism",
          "Ornithology",
          "Consumer economics",
          "Solid mechanics",
          "Field ministry",
          "User experience design",
          "Observational astronomy",
          "Speleology",
          "Accounting",
          "Music history",
          "Military campaign",
          "Peace education",
          "Spoken word",
          "Computer-aided engineering",
          "Environmental engineering",
          "Cardiology",
          "Storytelling",
          "Latin american studies",
          "Aeronautics",
          "Art education",
          "Quantum mechanics",
          "Nanoengineering",
          "Organometallic chemistry",
          "Cultural studies",
          "Personal fitness training",
          "Military geography",
          "Social philosophy",
          "Software engineering",
          "Political anthropology",
          "Pharmacognosy",
          "Reading education",
          "Policy sociology",
          "Biomechanics",
          "Interior architecture",
          "Bibliometrics",
          "Prosthodontics",
          "Asian psychology",
          "Contemporary philosophy",
          "Museology",
          "Geology",
          "Traffic psychology",
          "K-theory",
          "American studies",
          "Comparative religion",
          "Psychology",
          "Interior design",
          "Computer programming",
          "Radiochemistry",
          "Industry",
          "Non-euclidean geometry",
          "Ethnology",
          "Cosmetology",
          "Military medicine",
          "Child psychopathology",
          "Containment",
          "Dermatopathology",
          "Civil defense",
          "Automata theory",
          "Performance poetry",
          "Condensed matter physics",
          "Interlinguistics",
          "Metaphysics",
          "Counseling psychology",
          "Highway safety",
          "Polymer chemistry",
          "Sustainable development",
          "Sociology of knowledge",
          "Bilingual education",
          "Digital economy",
          "Calculus",
          "Acoustics",
          "Pharmacy",
          "Response surface methodology",
          "Men's studies",
          "Oncology",
          "Cloud computing",
          "Philosophy of pain",
          "Philosophy of science",
          "Hydrology/hydrography",
          "Lexicology",
          "Scholasticism",
          "Game theory",
          "Respiratory therapy",
          "Aftertaste",
          "Hepatology",
          "Conventional",
          "Sociolinguistics",
          "International law",
          "Criminal psychology",
          "Communication design",
          "Psychopathology",
          "Public sociology",
          "Actuarial science",
          "Real options analysis",
          "Urban geography",
          "Palatability",
          "Sedimentology",
          "Health policy",
          "Travel",
          "Survey methodology",
          "Cultural geography",
          "Exercise physiology",
          "Systems psychology",
          "History",
          "Health psychology",
          "Visual sociology",
          "Highway engineering",
          "Criminology",
          "Plant science",
          "Dynamical systems",
          "Cardiothoracic surgery",
          "Evolutionary biology",
          "Near eastern archaeology",
          "Literary genre",
          "Curriculum and instruction",
          "High-energy astrophysics",
          "Industrial engineering",
          "Outdoor education",
          "Numerical simulations",
          "Political philosophy",
          "Forensic science",
          "Mobile computing",
          "Public finance",
          "Nanotechnology",
          "Petroleum engineering",
          "Russian and eastern european studies",
          "Fisheries management",
          "Substantive law",
          "Social network analysis",
          "Anarchism",
          "Pharmaceutical policy",
          "Developmental psychology",
          "Arcade game",
          "Bootstrap",
          "Asian history",
          "Computer science",
          "Cooperative learning",
          "Liturgy",
          "Reasoning errors",
          "Vlsi design",
          "Intuitionistic logic",
          "German studies",
          "Indo-european studies",
          "Native american religions",
          "Socioeconomics",
          "Mathematical chemistry",
          "World literature",
          "White studies",
          "Teleology",
          "Community practice",
          "Philosophy of action",
          "Sociology of social movements",
          "Health geography",
          "Sociology of leisure",
          "Campaigning",
          "British literature",
          "Creative writing",
          "Cytology",
          "Navigation",
          "Physical activity",
          "Traumatology",
          "Social dynamics",
          "Psycholinguistics",
          "Public relations",
          "Community informatics",
          "Sociology of law",
          "Sonochemistry",
          "Business english",
          "Systems immunology",
          "Ring theory",
          "Podiatry",
          "Port management",
          "Popular culture studies",
          "Philosophy of war",
          "Lattice theory",
          "Structural engineering",
          "Sociology of health and illness",
          "Flavor",
          "School psychology",
          "Food preparation",
          "Clinical immunology",
          "Human resources management",
          "Determinism and free will",
          "Synthetic biology",
          "Philosophy of language",
          "Slot machine",
          "Warrior",
          "Type design",
          "Oenology",
          "Rhetoric",
          "Occult",
          "Neurosurgery",
          "Sociology of motherhood",
          "Biophysics",
          "Food security",
          "Technical writing",
          "Business administration",
          "Anarchist economics",
          "Recreation therapy",
          "Cold war (general term)",
          "International relations",
          "Digital humanities",
          "Comparative politics",
          "Russian history",
          "Visual communication",
          "Interstellar medium",
          "Psychological anthropology",
          "Military sociology",
          "Industrial design",
          "Fashion design",
          "Broadcast journalism",
          "Sustainability studies",
          "Malacology",
          "Choreography",
          "Geometric number theory",
          "Scientific history",
          "Agrochemistry",
          "Institutional economics",
          "Regulation",
          "Oology",
          "Industrial",
          "Prehistoric",
          "Paleoanthropology",
          "Food photography",
          "World history",
          "Modern",
          "Planetary science",
          "Physical organic chemistry",
          "Operating systems",
          "Religious education techniques",
          "Peace and conflict studies",
          "Marxian economics",
          "Polymer science",
          "Hoax",
          "Spirituality",
          "Object-oriented programming",
          "Geometric topology",
          "Philosophy of social science",
          "Orthopedic surgery",
          "Sociology of risk",
          "School social work",
          "Humanism",
          "Philosophy of artificial intelligence",
          "Medieval",
          "Market economy",
          "Nuclear",
          "Audio game",
          "Unconventional",
          "Human sexual behavior",
          "User experience evaluation",
          "Fiction writing",
          "Quantum field theory",
          "Information technology",
          "Mining engineering",
          "Rehabilitation medicine",
          "Arithmetic combinatorics",
          "Computational biology",
          "Experimental archaeology",
          "Optical physics",
          "Electronic media",
          "Genetics",
          "Proof theory",
          "Social geography",
          "Political sociology",
          "Machine learning",
          "Philosophy of law",
          "Thermodynamics",
          "Business",
          "Systems analysis",
          "Participatory economics",
          "Galois geometry",
          "Mesosociology",
          "Linguistic anthropology",
          "Comparative psychology",
          "Data mining",
          "Socialist economics",
          "Sociology of childhood",
          "Distributed computing",
          "Ecclesiology",
          "Internet, world wide web",
          "Criminal law",
          "Optometry",
          "Comparative anatomy",
          "Pathology",
          "Space",
          "Waste management",
          "Process design",
          "Military exercises",
          "Espionage",
          "Game design",
          "Buddhist studies",
          "Orchestral conducting",
          "Mercantile law",
          "Economic geography",
          "Chamber music",
          "Coastal management",
          "Homological algebra",
          "Language education",
          "Social capital",
          "Systemic therapy",
          "Dance",
          "Fiscal policy",
          "Environmental history",
          "Social constructionism",
          "Bioengineering",
          "Food presentation",
          "Economic policy",
          "Control systems",
          "Clinical microbiology",
          "Technology education",
          "Industrial organization",
          "Biochemistry",
          "Molecular genetics",
          "Growth economics",
          "Special education",
          "Public policy doctrine",
          "Gemology",
          "Renewable energy policy",
          "Mammalogy",
          "African religions",
          "Scandinavian studies",
          "Jewish studies",
          "Chemical biology",
          "Psychophysics",
          "Sterilization",
          "Systems engineering",
          "Masculine psychology",
          "Feminist economics",
          "Organ and historical keyboards",
          "International affairs",
          "Social anthropology",
          "Non-governmental organization (ngo) administration",
          "Offensive",
          "Sociology of work",
          "Grid computing",
          "Black psychology",
          "Stochastic process",
          "Journalism",
          "Enology",
          "Leadership",
          "Dogmatic theology",
          "Finite geometry",
          "Clinical pathology",
          "English literature",
          "Personal trainer",
          "Fuzzy logic",
          "Sport psychology",
          "Herpetology",
          "Forgery",
          "Telecommunications engineering",
          "Legal education",
          "Zootomy",
          "Sociology of agriculture",
          "Conservation psychology",
          "Representation theory",
          "History of computer hardware",
          "Sociology of aging",
          "Gastroenterology",
          "Acquired taste",
          "Slavic studies",
          "Pastoral counseling",
          "Formal languages",
          "Morphology",
          "Immunology",
          "Secondary education",
          "Australian studies",
          "Health informatics/clinical informatics",
          "Chaos theory",
          "Pedagogy",
          "Environmental economics",
          "Medical anthropology",
          "Battlespace",
          "Cybernetics",
          "Indonesian history",
          "Aesthetics",
          "Computational systems biology",
          "Agricultural policy",
          "Systematics",
          "Political behavior",
          "Biomechanical engineering",
          "Agrology",
          "Agroecology",
          "Psychological",
          "Paralegal studies",
          "Newspaper",
          "Computational mathematics",
          "Materiel",
          "Dermatology",
          "Neurology",
          "Information retrieval",
          "Decorative arts",
          "Silviculture",
          "Folklore",
          "Medical physics",
          "Artificial intelligence",
          "Fault-tolerant computing",
          "Volcanology",
          "General topology",
          "Sociology of government",
          "Nursing",
          "Differential algebra",
          "Cartography",
          "Dental hygiene and epidemiology",
          "Land",
          "Integral geometry",
          "Quantum gravity",
          "Mechanics",
          "X-ray astronomy",
          "Artisanal food",
          "Jainism",
          "Television studies",
          "Epidemiology",
          "Neuro-ophthalmology",
          "Vaccination policy",
          "Family psychology",
          "Interpretive sociology",
          "Animal communication",
          "Sea",
          "Cuisine",
          "Biological psychology",
          "Doxastic logic",
          "Graphic arts",
          "Security policy",
          "Botany",
          "Electronic",
          "Industrial and labor relations",
          "Sumerian religion",
          "Andrology",
          "Computer engineering",
          "Stellar nucleosynthesis",
          "Media psychology",
          "Church music",
          "Energy economics",
          "Conchology",
          "Occupational health psychology",
          "Convex geometry",
          "Climate change policy",
          "Disarmament",
          "Clinical neuropsychology",
          "Personality psychology",
          "Historical theology",
          "African studies",
          "Activism",
          "Alternative medicine",
          "Social control",
          "Ecosystem ecology",
          "Gnosticism",
          "Logical reasoning",
          "Playwrighting",
          "Outdoor activity",
          "Psychoanalysis",
          "Primatology",
          "Environmental geography",
          "Stochastic processes",
          "Applied linguistics",
          "Geophysics",
          "Caodaism",
          "Petrochemistry",
          "Iranian studies",
          "Human resources",
          "Sociology of the body",
          "Gynaecology",
          "Property law",
          "Sociology of markets",
          "Literary journalism",
          "Supramolecular chemistry",
          "Thermochemistry",
          "Film genre",
          "Object database",
          "Sociology of fatherhood",
          "Medical cybernetics",
          "Histopathology",
          "Human physiology",
          "Analytic philosophy",
          "Historical geography",
          "Mythology",
          "Palaeogeography",
          "Strategic studies",
          "Process engineering",
          "Discrete geometry",
          "Comparative sociology",
          "Scientific computing",
          "Diet",
          "Cyber",
          "Counselor education",
          "Rheumatology",
          "Sports medicine",
          "Siege",
          "Type theory",
          "Monetary economics",
          "Governmental affairs",
          "Digital sociology",
          "Carcinology",
          "Digital culture",
          "Textiles",
          "Infectious disease",
          "Maneuver",
          "Ethology",
          "Semiconductors",
          "Molecular physics",
          "Natural resource sociology",
          "Modal logic",
          "Behavioural economics",
          "Multilinear algebra",
          "Compilers",
          "Marine biology",
          "Archival science",
          "Vehicle dynamics",
          "Food engineering",
          "Marine transportation",
          "Computational number theory",
          "Historical musicology",
          "Food choice",
          "Perceptual control theory",
          "Robotics",
          "Concurrent programming",
          "Managerial economics",
          "Arms race",
          "Athletic director",
          "Sportscasting",
          "Immigration policy",
          "Human sexuality",
          "Classical language",
          "Housing",
          "Social movements",
          "Creative nonfiction",
          "Clandestine operation",
          "Combinatorics",
          "Measure theory",
          "Bariatric surgery",
          "Combat",
          "Athletic training",
          "Preventive medicine",
          "Behavioral neuroscience",
          "Anatomy",
          "Power engineering",
          "Social engineering",
          "Transport phenomena",
          "Computational complexity theory",
          "Randomized algorithms",
          "Probability theory",
          "Corporate law",
          "Social stratification",
          "Acoustical engineering",
          "Economic anthropology",
          "Microeconomics",
          "Reaction engineering",
          "Regional geography",
          "Neurochemistry",
          "Microwave astronomy",
          "Aristotelianism",
          "Endemic warfare",
          "Optical engineering",
          "Music theory",
          "Aerobics",
          "Complex analysis",
          "Sports biomechanics",
          "Post-modern literature",
          "Algorithms",
          "Painting",
          "Projective geometry",
          "Historic preservation",
          "Mathematical logic",
          "Abnormal psychology",
          "Laws of war",
          "Eastern philosophy",
          "Organization theory",
          "Air",
          "Mathematical biology",
          "Quantum physics",
          "Poetics",
          "Social change",
          "Primary care",
        ]
      end
    end
  end
end
