module Kitbash
  module Synonyms
    module Bulk
      @sport = [
        "Shaolin kung fu",
        "Fox hunting",
        "Casterboarding",
        "Touch rugby",
        "Mountainboarding",
        "Target shooting",
        "Land speed records",
        "Traditional climbing",
        "Ribbon",
        "Road bicycle racing",
        "Auto race",
        "Clay pigeon shooting",
        "Goat tying",
        "Starcraft",
        "Butts up",
        "Wall game",
        "Australian football",
        "Crossfit",
        "Backpacking",
        "Demolition derby",
        "Frontenis",
        "Arimaa",
        "Autocross",
        "Surf fishing",
        "Regularity rally",
        "Boli khela",
        "Kilikiti",
        "Mixed climbing",
        "Aerobatics",
        "Pencak silat",
        "Shootfighting",
        "Greco-roman wrestling",
        "Alpine skiing",
        "Fujian white crane",
        "10k run",
        "Rock fishing",
        "Indoor archery",
        "Eton fives",
        "Decathlon",
        "Paleta frontón",
        "Egyptian stick fencing",
        "Fistball",
        "Show jumping",
        "Wheelchair basketball",
        "Pentathlon",
        "Baseball pocket billiards",
        "Yağlı güreş",
        "Moscow broomball",
        "Target archery",
        "Aerial silks",
        "Toboggan",
        "Skateboarding",
        "Windsurfing",
        "Bando",
        "Snowboarding",
        "Judo",
        "Freeboating",
        "Parachuting",
        "Varzesh-e pahlavani",
        "Indoor cricket",
        "Ice climbing",
        "Dodgeball",
        "Carom billiards",
        "Axe throwing",
        "Miniature bull riding",
        "Laser tag",
        "Iaidō",
        "Novuss",
        "Cammag",
        "Match play",
        "Greek wrestling",
        "Kneeboarding",
        "Sinuca brasileira",
        "Czech handball",
        "Beagling",
        "Team penning",
        "Pickup truck racing",
        "Rafting",
        "Double disc court",
        "Ball",
        "Caid",
        "Land windsurfing",
        "Sudoku",
        "Powerlifting",
        "Frisbee",
        "Naginatajutsu",
        "F1 powerboat racing",
        "Base jumping",
        "Parasailing",
        "Sprint football",
        "Cliff diving",
        "Choi kwang-do",
        "Eskrima",
        "Crossminton",
        "Kyūdō",
        "Snorkelling",
        "Taidō",
        "Pocket billiards",
        "Hardcourt bike polo",
        "Badminton",
        "Deaf basketball",
        "Figure skating",
        "Battōjutsu",
        "Stihl timbersports series",
        "Bodybuilding",
        "Frisian handball",
        "Creeking",
        "Ekiden",
        "Speed skiing",
        "Sword fighting",
        "Cornish wrestling",
        "International rules football",
        "Artistic pool",
        "Beach soccer",
        "Free-style moto",
        "Taekwondo",
        "Parallel bars",
        "Futebol de salão",
        "Wing chun",
        "Wallyball",
        "Skimboarding",
        "Floor",
        "Rugby tens",
        "Streetluge",
        "Noodling",
        "Danish longball",
        "Grappling",
        "Flyak",
        "Sumo",
        "Cirit",
        "Production car racing",
        "Bokator",
        "Ice yachting",
        "Truck racing",
        "Midget car racing",
        "Supersport racing",
        "Ball hockey",
        "Hardball squash",
        "Hooverball",
        "American handball",
        "Hopper ballooning",
        "Bujinkan",
        "Bartitsu",
        "Stunt",
        "Eight-ball",
        "Sprint car racing",
        "Air racing",
        "Lapta",
        "Inline hockey",
        "Trap shooting",
        "Model aerobatics",
        "Krav maga",
        "Skeet shooting",
        "Nine-a-side footy",
        "Bronc riding",
        "Pool",
        "Sipa",
        "Debating",
        "Cowboy polo",
        "Bicycle polo",
        "Canoeing",
        "Boxing",
        "Streetboarding",
        "Indoor soccer",
        "Capture the flag",
        "Papi fut",
        "Vovinam",
        "Enduro",
        "One day international",
        "Surfing",
        "Wolf hunting",
        "Qianball",
        "Half marathon",
        "Ultralight aviation",
        "Offshore powerboat racing",
        "Keep away",
        "Dirt track racing",
        "Woggabaliri",
        "Backstroke",
        "Town ball",
        "Killer",
        "Elephant polo",
        "Power hockey",
        "Corkball",
        "Darts",
        "Sledge hockey",
        "Cuju",
        "Endurance racing",
        "Biathlon",
        "Five-pins",
        "Composite rules shinty-hurling",
        "Gliding",
        "Lancashire wrestling",
        "Dressage",
        "Uneven bars",
        "Peteca",
        "Cheerleading",
        "Hunter",
        "Hare coursing",
        "Club",
        "Saddle bronc riding",
        "Pommel horse",
        "Ringette",
        "Bagatelle",
        "Squirt boating",
        "Sport stacking",
        "Beach basketball",
        "Kalaripayattu",
        "Kumdo",
        "Archery",
        "Ki-o-rahi",
        "Water basketball",
        "Beach tennis",
        "Rc racing",
        "Yak polo",
        "Fly fishing",
        "Road racing",
        "Cowboy action shooting",
        "International fronton",
        "Single skating",
        "Chinese checkers",
        "Flutterguts",
        "Climbing",
        "Vigoro",
        "Time attack",
        "Tumbling",
        "Platform tennis",
        "Basque traditional weightlifting",
        "Outrigger canoeing",
        "Tractor pulling",
        "Beach volleyball",
        "Pair skating",
        "Kite buggy",
        "Speed-ball",
        "La soule",
        "Shidōkan karate",
        "Shinty",
        "Field target",
        "Northern praying mantis",
        "Polocrosse",
        "5k run",
        "Trick shot competition",
        "Camping",
        "Disc dog",
        "Matkot",
        "Foosball",
        "Mud bogging",
        "Downhill mountain biking",
        "Underwater ice hockey",
        "Diplomacy",
        "Competitive swimming",
        "Hana ichi monme",
        "Punchball",
        "Practical shooting",
        "Disc golf",
        "Rec footy",
        "Savate",
        "Old cat",
        "Hunter-jumpers",
        "Episkyros",
        "Cross-country skiing",
        "Four-ball",
        "Formula racing",
        "Volleyball",
        "Flying trapeze",
        "Hiking",
        "Kho kho",
        "Breaststroke",
        "Jousting",
        "Baton twirling",
        "Horse polo",
        "Wireball",
        "Football tennis",
        "Sandboarding",
        "Baguazhang",
        "Pole climbing",
        "Drifting",
        "Hurdles",
        "Rock climbing",
        "Gouren",
        "Racketball",
        "Wheelstand competition",
        "Aquathlon",
        "Metallic silhouette shooting",
        "Handball",
        "Superside",
        "Touring car racing",
        "Big-game fishing",
        "Artistic billiards",
        "Skiing",
        "Rugby league sevens",
        "Geocaching",
        "Miniten",
        "Kite landboarding",
        "Bar billiards",
        "Hillclimbing",
        "Aiki-jūjutsu",
        "Cross country",
        "Racewalking",
        "Catch wrestling",
        "Chicago",
        "Bullriding",
        "Freestyle swimming",
        "Monster truck",
        "Bouldering",
        "Fencing",
        "Ssireum",
        "Zen bu kan kempo",
        "Trapeze",
        "Barrel racing",
        "Squash",
        "Dota 2",
        "Board track racing",
        "Yukigassen",
        "Whitewater kayaking",
        "Woodsman",
        "Eclipse ball",
        "Wallball",
        "Curling",
        "Hang gliding",
        "Cockfighting",
        "Powerchair football",
        "Kajukenbo",
        "Stické",
        "Snow rugby",
        "Clash royale",
        "Hot box",
        "Wheelchair rugby league",
        "Kung fu",
        "Guts",
        "Vault",
        "Ice hockey",
        "Soft tennis",
        "Test cricket",
        "Spearfishing",
        "Underwater football",
        "Unicycling",
        "Airsoft",
        "Chinlone",
        "Rink bandy",
        "Free running",
        "Rally raid",
        "All-terrain vehicle competition",
        "Freestyle wrestling",
        "Scootering",
        "Rope climbing",
        "Street workout",
        "Camogie",
        "Buzkashi",
        "Xing yi quan",
        "Fastnet",
        "Street hockey",
        "Cushion caroms",
        "Folk wrestling",
        "Bo-taoshi",
        "Speed golf",
        "Banger racing",
        "Hoop",
        "Floorball",
        "Slow pitch",
        "Valencian frontó",
        "Canadian football",
        "Hockey",
        "Deep-water soloing",
        "Personal water craft",
        "Sport climbing",
        "Bat and trap",
        "Paintball",
        "Freestyle bmx",
        "Checkers",
        "T'ai chi ch'uan",
        "Freestyle football",
        "Stool ball",
        "Squash tennis",
        "Popinjay",
        "Royal shrovetide football",
        "Field archery",
        "Dragon boat racing",
        "Over",
        "Telemark skiing",
        "Biribol",
        "Rugby fives",
        "Mod league",
        "Rallying",
        "Marathon",
        "Karate",
        "Dodge disc",
        "Chess960",
        "Tower running",
        "Nordic combined",
        "Arena football",
        "Wakeboarding",
        "Mahjong",
        "Powerbocking",
        "Metro footy",
        "Rugby league",
        "Bobsleigh",
        "Amateur wrestling",
        "Acrobatic gymnastics",
        "Footbag net",
        "Brazilian jiu-jitsu",
        "Canoe polo",
        "Sport diving",
        "Waboba",
        "Grand prix motorcycle racing",
        "Aerobic gymnastics",
        "Twenty20",
        "Subak",
        "Surface finswimming",
        "Apnoea finswimming",
        "Wrestling",
        "Ba game",
        "Jōdō",
        "Folkrace",
        "Jet sprint boat racing",
        "Desert racing",
        "Six-man football",
        "Shurikenjutsu",
        "Field handball",
        "Rope jumping",
        "Skins game",
        "Silambam",
        "Spongee",
        "Casting",
        "Pelota mixteca",
        "Underwater hockey",
        "Patball",
        "Jianzi",
        "Strike",
        "Horseball",
        "Drag boat racing",
        "Hearthstone",
        "Scuba diving",
        "Cutthroat",
        "British baseball",
        "Roller hockey",
        "Big game hunting",
        "Kuk sool won",
        "Lelo burti",
        "Dancesport",
        "Speedball",
        "Skeleton",
        "Water polo",
        "Synchronized swimming",
        "Street football",
        "Krabi–krabong",
        "Stand up paddle boarding",
        "Track racing",
        "Shuai jiao",
        "Seven-ball",
        "High bar",
        "Knattleikr",
        "English billiards",
        "Fullbore target rifle",
        "Sailing",
        "Sports car racing",
        "Formula libre",
        "Cross-country rally",
        "Flight archery",
        "Schwingen",
        "Pesäpallo",
        "Mountaineering",
        "Rope",
        "Uppies and downies",
        "Jacquet",
        "Orienteering",
        "Marching band",
        "Powered hang glider",
        "Balance beam",
        "Indoor football",
        "Kendo",
        "Keepie uppie",
        "Skibobbing",
        "Scrub baseball",
        "Olympic weightlifting",
        "Kite fighting",
        "Snooker",
        "Volata",
        "Trampolining",
        "Collar-and-elbow",
        "Indoor netball",
        "Bumper pool",
        "Systema",
        "Heptathlon",
        "Hunting",
        "Harness racing",
        "Tennis polo",
        "Rossall hockey",
        "Calcio fiorentino",
        "Sikaran",
        "Tang soo do",
        "Sepak takraw",
        "Superbike racing",
        "Snowmobile racing",
        "Snow kiting",
        "Rotation",
        "Pankration",
        "Three sided football",
        "Pond hockey",
        "Softball",
        "Hydroplane racing",
        "High power rifle",
        "Xare",
        "Sanshou",
        "Jūkendō",
        "Racquets",
        "Bossaball",
        "Triathlon",
        "Freeboard",
        "Quizzing",
        "Slot car racing",
        "Eventing",
        "Steinstossen",
        "Four square",
        "Sambo",
        "Steer roping",
        "Kenjutsu",
        "Jogo do pau",
        "Mongolian wrestling",
        "Team roping",
        "Juggling",
        "Neppis",
        "Static trapeze",
        "Longboarding",
        "Sur-papakh",
        "Throwball",
        "Mancala",
        "English pleasure",
        "Benchrest shooting",
        "Equitation",
        "Kitesurfing",
        "Modern arnis",
        "Model aircraft",
        "One-pocket",
        "Aikido",
        "Kayaking",
        "Cycle speedway",
        "Cnapan",
        "Dominoes",
        "Harrow football",
        "Powered paragliding",
        "Skydiving",
        "Ninjutsu",
        "Surfboat",
        "Masters football",
        "Hurling",
        "Stock car racing",
        "Unicycle hockey",
        "Speedcubing",
        "Gaelic football",
        "Red rover",
        "Robot combat",
        "League of legends",
        "Backgammon",
        "Ice fishing",
        "Pradal serey",
        "Snowshoe running",
        "Field lacrosse",
        "Water volleyball",
        "Cutting",
        "Banzai skydiving",
        "Racketlon",
        "Individual medley",
        "Paddleboarding",
        "Goalball",
        "Pehlwani",
        "Campdrafting",
        "Rowing",
        "Miniature golf",
        "Cross-country mountain biking",
        "Rugby sevens",
        "Golf",
        "Flag football",
        "Underwater rugby",
        "Rogaining",
        "Beach handball",
        "Canyoning",
        "Street unicycling",
        "Sporting clays",
        "Harpastum",
        "Samoa rules",
        "Reining",
        "Horse racing",
        "Quidditch",
        "Torball",
        "Race of champions",
        "Immersion finswimming",
        "Artistic cycling",
        "Bodyboarding",
        "Palla",
        "Steeplechase",
        "Endurance riding",
        "Kabaddi",
        "Intercrosse",
        "Shogi",
        "Rinkball",
        "Pickleball",
        "Dice stacking",
        "Kenpō",
        "Kurash",
        "Bank pool",
        "Three-cushion",
        "Equestrian vaulting",
        "Track cycling",
        "Ga-ga",
        "Supermoto",
        "Six-red snooker",
        "Land sailing",
        "Gig racing",
        "Underwater orienteering",
        "Marn grook",
        "Matball",
        "Street racing",
        "Kick the can",
        "Paramotoring",
        "Mountain running",
        "Barrel jumping",
        "Vintage racing",
        "Skysurfing",
        "Rounders",
        "Ski touring",
        "Cycle polo",
        "Human powered aircraft",
        "Short track motor racing",
        "Muay thai",
        "Slacklining",
        "Chinese handball",
        "Off-road racing",
        "Sōjutsu",
        "Slamball",
        "Risk",
        "Paralympic football",
        "Nordic skiing",
        "Super smash bros. melee",
        "Road running",
        "Austus",
        "Single scull",
        "Capoeira",
        "Kickboxing",
        "Highland games",
        "Cross-country running",
        "Tent pegging",
        "Kickball",
        "Jai alai",
        "Ringball",
        "Motocross",
        "Racquetball",
        "Hojōjutsu",
        "Sea kayaking",
        "Formula student",
        "Rocket league",
        "Kemari",
        "Pole bending",
        "Box lacrosse",
        "Coastal and ocean rowing",
        "Jeu de paume",
        "Gungdo",
        "Indoor field hockey",
        "Tag rugby",
        "Haxey hood",
        "Boffer fighting",
        "Tee ball",
        "Ball badminton",
        "Lacrosse",
        "Ultimate frisbee",
        "Ladies' gaelic football",
        "Mob football",
        "Skater hockey",
        "Freestyle footbag",
        "Underwater target shooting",
        "Straight pool",
        "Cowboy",
        "Wushu",
        "Australian handball",
        "Ice racing",
        "Rodeo",
        "Model aircraft racing",
        "Cricket",
        "Team handball",
        "Streetball",
        "Brännboll",
        "Pato",
        "Go",
        "Yubi lakpi",
        "Reversi",
        "Unicycle trials",
        "Go-moku",
        "Sholo guti",
        "Oina",
        "Touch football",
        "Women's lacrosse",
        "Futsal",
        "Angling",
        "Shōrin-ryū shidōkan",
        "Glima",
        "Tag",
        "Fives",
        "Competitive dancing",
        "Lethwei",
        "Freediving",
        "Professional wrestling",
        "Three-ball",
        "Drag racing",
        "Off-roading",
        "Paralympic volleyball",
        "Sprint",
        "Medley relay",
        "Rugby league nines",
        "Gatka",
        "Deer hunting",
        "Cyclo-cross",
        "Iaijutsu",
        "Dirt jumping",
        "Still rings",
        "Hunger games",
        "Tennis",
        "Gaelic handball",
        "American flag rugby",
        "Valencian pilota",
        "Hapkido",
        "Limited overs cricket",
        "Rallycross",
        "Letterboxing",
        "Overwatch",
        "Unicycle basketball",
        "Calf roping",
        "Palant",
        "Fell running",
        "Silat",
        "Field game",
        "Broomball",
        "Xiangqi",
        "Swamp football",
        "Parkour",
        "Fishing",
        "Draughts",
        "Abseiling",
        "Taekkyeon",
        "Grasstrack",
        "Blackball",
        "Autograss",
        "Field hockey",
        "Hwa rang do",
        "Rocball",
        "Newcomb ball",
        "Russian pyramid",
        "Gymkhana",
        "Netball",
        "Wiffleball",
        "Trail running",
        "Freestyle skiing",
        "Roping",
        "Charreada",
        "Urban golf",
        "Gymnastics",
        "Stickball",
        "Eton wall game",
        "Duathlon",
        "Artistic gymnastics",
        "Polo",
        "Elle",
        "Vajra-mushti",
        "Freestyle motocross",
        "Model yacht racing",
        "Wakesurfing",
        "Steer wrestling",
        "Walking",
        "Strength athletics",
        "Luge",
        "Wingsuit flying",
        "Kyūjutsu",
        "Ultramarathon",
        "Football",
        "Bifins",
        "Bmx",
        "Sogo",
        "Skijoring",
        "Goaltimate",
        "Five-a-side football",
        "Nine-man football",
        "Chilean rodeo",
        "Riverboarding",
        "Baseball",
        "Freestyle",
        "Jittejutsu",
        "Kart racing",
        "Skyrunning",
        "Okinawan kobudō",
        "Ice speedway",
        "Hornussen",
        "Tetrathlon",
        "Universal football",
        "Diving",
        "Tchoukball",
        "The massachusetts game",
        "Cornish hurling",
        "Supercross",
        "Basque pelota",
        "Bareback bronc riding",
        "Metallic silhouette",
        "Modern pentathlon",
        "Underwater photography",
        "Mixed martial arts",
        "Tt racing",
        "Indoor enduro",
        "Sport kite",
        "Trial",
        "Shorinji kempo",
        "Jorkyball",
        "Breakaway roping",
        "Hide and seek",
        "Padel",
        "Butterfly stroke",
        "Shoot boxing",
        "Surf kayaking",
        "Gridiron football",
        "Jeet kune do",
        "Legends car racing",
        "Cribbage",
        "Eight-man football",
        "Icosathlon",
        "Real tennis",
        "Bicycle",
        "Dinghy sailing",
        "Ice dancing",
        "Underwater cycling",
        "Cestoball",
        "Oztag",
        "Speed pool",
        "Rhythmic gymnastics",
        "Basketball",
        "Disc golf (urban)",
        "Card stacking",
        "Aid climbing",
        "Sledding",
        "Jugger",
        "Cycling",
        "Bottle pool",
        "Dumog",
        "Nguni stick-fighting",
        "Sport fishing",
        "Kiteboarding",
        "American football",
        "Snowkiting",
        "Marine corps martial arts program",
        "Coasteering",
        "Motorcycle drag racing",
        "Jujutsu",
        "White water rafting",
        "Vale tudo",
        "Adventure racing",
        "Bowlliards",
        "Mini rugby",
        "Snooker plus",
        "Segway polo",
        "Cluster ballooning",
        "Waymarking",
        "Bandy",
        "Paragliding",
        "Korfball",
        "Motorcycle speedway",
        "Rugby football",
        "Balkline and straight rail",
        "Beach rugby",
        "Stratego",
        "Ski jumping",
        "Footvolley",
        "Chess",
        "Kin-ball",
        "Mountain unicycling",
        "Nine-ball",
        "Squash 57",
        "Scrabble",
        "Malla-yuddha",
        "British bulldogs",
        "Kelly pool",
        "Bushwhacking",
        "Table tennis",
        "Ten-ball",
      ]

      @study = [
        "Iranian history",
        "Entrepreneurial economics",
        "Cooking",
        "Food engineering",
        "Substantive law",
        "Biomolecular engineering",
        "Political sociology",
        "Anthropology of religion",
        "Social capital",
        "Complex analysis",
        "Group theory",
        "Ordinary differential equations",
        "Hydrology",
        "Ontology",
        "Virtue ethics",
        "Partial differential equations",
        "Architectural engineering",
        "Internal medicine",
        "Programming languages",
        "Time geography",
        "Probability theory",
        "Carcinology",
        "Medical education",
        "Management cybernetics",
        "Legal education",
        "Network-centric warfare",
        "Live action",
        "Biochemistry",
        "Woodwinds, brass, and percussion",
        "Travel",
        "Computer graphics",
        "Nursing education",
        "Analysis",
        "Synchronic linguistics",
        "Philosophy of biology",
        "Linnaean taxonomy",
        "Infrastructure",
        "Management information systems",
        "Music",
        "Economic policy",
        "System dynamics",
        "Developmental systems theory",
        "Historical musicology",
        "Defensive",
        "Planktology",
        "Polymer chemistry",
        "Medieval",
        "Classical archaeology",
        "Geometric number theory",
        "Differential psychology",
        "Organometallic chemistry",
        "Creative nonfiction",
        "Systems analysis",
        "Pastoral theology",
        "Demography",
        "White studies",
        "Sound and music computing",
        "Philosophy of pain",
        "Religious war",
        "Orthodontics",
        "Family law",
        "Thermochemistry",
        "Agrology",
        "Ergodic theory",
        "Creative writing",
        "Constitutional law",
        "Homological algebra",
        "Print journalism",
        "Pulmonology",
        "Control systems",
        "Business administration",
        "Cultural sociology",
        "Animal husbandry",
        "Conservation science",
        "Psychological anthropology",
        "Topology",
        "Sociology of punishment",
        "Justification",
        "Actuarial science",
        "Geodesy",
        "Drug policy reform",
        "Philosophy of artificial intelligence",
        "Geology",
        "Technical drawing",
        "Mastery learning",
        "Cardiology",
        "Scandinavian studies",
        "School psychology",
        "Indo-european studies",
        "Regulation",
        "Agricultural policy",
        "Infectious disease",
        "Christianity",
        "Archival science",
        "Conchology",
        "Marine biology",
        "Economic development",
        "Laws of war",
        "Language policy",
        "Philosophy of war",
        "Culinary arts",
        "Sociology of agriculture",
        "Nephrology",
        "Computational fluid dynamics",
        "Finite element analysis",
        "Radiology",
        "Sociology of leisure",
        "Collateral damage",
        "Organizational psychology",
        "Philosophy of economics",
        "Physical cosmology",
        "Logistics",
        "Market economy",
        "Philology",
        "Sociotechnical systems theory",
        "Community informatics",
        "Communication studies",
        "Advertising",
        "Pediatrics",
        "General systems theory",
        "Public speaking",
        "Child welfare",
        "Feminist geography",
        "Medical physics",
        "Counter-terrorism",
        "Technology and equipment",
        "Nanomaterials",
        "Data structures",
        "Military campaign",
        "Systematic musicology",
        "Palaeoclimatology",
        "Sociology of risk",
        "Morale",
        "Organizational behavior",
        "Animal rights",
        "Medical social work",
        "Perceptual control theory",
        "Femtochemistry",
        "Telecommunications engineering",
        "Women's studies",
        "Sociology of emotions",
        "History of philosophy",
        "Storytelling",
        "Outdoor activity",
        "Criminal law",
        "Nutrition",
        "Instrumentation engineering",
        "Interactionism",
        "Gravitational astronomy",
        "Time series",
        "Systems neuroscience",
        "Computer security and reliability",
        "Recreation ecology",
        "Green chemistry",
        "Supramolecular chemistry",
        "Ethnoecology",
        "Stellar evolution",
        "Remote sensing",
        "Intercultural communication",
        "Operating systems",
        "Jainism",
        "Solid state physics",
        "Crystallography",
        "User experience evaluation",
        "Social change",
        "Ubiquitous computing",
        "Modern language",
        "Corrections",
        "Solid mechanics",
        "Multilinear algebra",
        "Contract law",
        "Economic anthropology",
        "Decontamination",
        "Earth systems engineering and management",
        "Highway engineering",
        "Transport economics",
        "Grid computing",
        "Music history",
        "Alternative medicine",
        "Astronautics",
        "Sea",
        "Geriatrics",
        "European studies",
        "Strategy",
        "Plasma physics",
        "Humanistic sociology",
        "American politics",
        "Cytohematology",
        "Intellectual history",
        "Toy and amusement design",
        "Proxy war",
        "Systems psychology",
        "Bioethics",
        "Phonology",
        "Cultural psychology",
        "Maneuver",
        "Early childhood education",
        "Population genetics",
        "Dentistry",
        "Batoning",
        "Complex system",
        "Public safety",
        "Educational psychology",
        "Endemic warfare",
        "Knowledge policy",
        "Mathematical biology",
        "Religious education techniques",
        "Human sexual behavior",
        "Experimental archaeology",
        "Combinatorics",
        "Scriptural study and languages",
        "Gerontology",
        "Military simulation",
        "Oenology",
        "Neuro-ophthalmology",
        "Spirituality",
        "Jurisprudence",
        "Functional analysis",
        "Nuclear physics",
        "Unconventional",
        "Applied linguistics",
        "Psychoanalysis",
        "Food security",
        "Newtonian dynamics",
        "Film genre",
        "Gamma ray astronomy",
        "Environmental ethics",
        "Experimental economics",
        "Military psychology",
        "Political anthropology",
        "Sociology of organizations",
        "Observational astronomy",
        "Asian studies",
        "Animal communications",
        "Orthopedic surgery",
        "Hydraulic engineering",
        "Information theory",
        "Macroeconomics",
        "Helminthology",
        "Harmonic analysis",
        "Algebraic (symbolic) computation",
        "Food photography",
        "Distance education",
        "Optical engineering",
        "Geopolitics (political geography)",
        "Molecular virology",
        "New media journalism",
        "Acquired taste",
        "Sexology",
        "Ethology",
        "Offensive",
        "Policy studies",
        "Quantum field theory",
        "Human resources",
        "Art education",
        "Power engineering",
        "Reading education",
        "Pharmacognosy",
        "Differential topology",
        "Rheumatology",
        "Internet sociology",
        "Procedural law",
        "Traditional food",
        "Asian history",
        "Literary criticism",
        "Artificial neural network",
        "Sociology of immigration",
        "Galois geometry",
        "Comparative education",
        "Citation analysis",
        "Clinical physiology",
        "Behavioral neuroscience",
        "Mercantile law",
        "Parallel algorithms",
        "Collective bargaining",
        "Sociology of education",
        "Geophysics",
        "Chemical biology",
        "Pure sociology",
        "Aristotelianism",
        "Indigenous psychology",
        "Assassination",
        "Fiction writing",
        "Cultural studies",
        "Military geography",
        "Environmental law",
        "Limnology",
        "Computer program",
        "Operations research",
        "Early music",
        "Solid-state chemistry",
        "Dental hygiene and epidemiology",
        "Affect control theory",
        "Consumer economics",
        "Exercise physiology",
        "Ethnography",
        "Teratology",
        "Philosophy of engineering",
        "Labor law",
        "Urology",
        "Pedagogy",
        "Criminology",
        "Painting",
        "Comparative sociology",
        "Teleology",
        "Space",
        "Linguistic anthropology",
        "Sociology of music",
        "Support vector machine",
        "Forgery",
        "Law enforcement",
        "Philosophy of psychology",
        "Scheduling",
        "Vocational education",
        "Internet, world wide web",
        "Food studies",
        "Structural equation model",
        "Masculine psychology",
        "Queer theory",
        "Commercial policy",
        "Economics",
        "Photography",
        "Foreign policy",
        "Human services",
        "Food preparation",
        "Fluid dynamics",
        "Morphology",
        "Microeconomics",
        "Computational biology",
        "Civil procedure",
        "Climate change policy",
        "Private military company",
        "Second-order cybernetics",
        "Anatomical pathology",
        "Universal algebra",
        "Astrophysical plasma",
        "Bootstrap",
        "General practice",
        "American studies",
        "Number theory",
        "Agricultural economics",
        "Transport phenomena",
        "P-adic analysis",
        "Dynamic programming",
        "Earthquake engineering",
        "Criminal psychology",
        "Renewable energy policy",
        "Public policy",
        "Problem solving",
        "Political culture",
        "Chinese sociology",
        "Flow chemistry",
        "Ranks",
        "Spoken word",
        "Botany",
        "Living systems theory",
        "Osteopathy",
        "Biogeography",
        "Graphic arts",
        "Social movements",
        "Private defense agency",
        "E-business",
        "Cooperative learning",
        "Music therapy",
        "Chaos theory",
        "Cryogenics",
        "Epistemology",
        "Textiles",
        "Ethnolinguistics",
        "Game design",
        "Public health",
        "Magnetohydrodynamics",
        "Uv astronomy",
        "Environmental communication",
        "Logical reasoning",
        "Tourism geography",
        "Numerical simulations",
        "Green economics",
        "Victimology",
        "Social engineering",
        "Corporations",
        "Digital sociology",
        "Sociology of health and illness",
        "Institutional economics",
        "Applied philosophy",
        "Human biology",
        "Celtic studies",
        "Biblical studies",
        "Sociology of space",
        "Ecclesiology",
        "Nuclear",
        "Containment",
        "Incomes policy",
        "Philosophy of space and time",
        "Sinology",
        "Environmental policy",
        "Information management",
        "Marine chemistry",
        "Sociology of food",
        "Physiotherapy",
        "International relations",
        "Gastronomy",
        "Oology",
        "Drawing",
        "Sex education",
        "Wildlife management",
        "Digital economy",
        "Dermatology",
        "Emergency services",
        "Naval engineering",
        "Materials science and engineering",
        "Petrochemistry",
        "Endocrinology",
        "Classical language",
        "Cold war (general term)",
        "Neuroeconomics",
        "Distributed computing",
        "Television",
        "Figurational sociology",
        "Trauma surgery",
        "Physical organic chemistry",
        "Theater (warfare)",
        "Cardiac electrophysiology",
        "Psychology of religion",
        "Computational chemistry",
        "Gene-culture coevolution",
        "Ophthalmology",
        "Sterilization",
        "Federal law",
        "Military science",
        "Atmospheric chemistry",
        "Pharmacy",
        "Sociology of marriage",
        "Linear programming",
        "Digital asset",
        "Embryology",
        "Aquaculture",
        "Policy analysis",
        "Phenomenology",
        "Arms race",
        "Intelligence",
        "Biological",
        "Surgical pathology",
        "Sociology of sport",
        "Humanism",
        "Interlinguistics",
        "Zootomy",
        "Ecosystem ecology",
        "Applied psychology",
        "World englishes",
        "Elementary education",
        "Engineering physics",
        "Campaigning",
        "Nursing",
        "Syntax",
        "Caodaism",
        "Waste management",
        "Respiratory therapy",
        "Artificial intelligence",
        "Chamber music",
        "Sonochemistry",
        "Hindu ethics",
        "Hydrogeology",
        "Artisanal food",
        "Differential algebra",
        "Pharmaceutical sciences",
        "General topology",
        "Audio game",
        "Chemical engineering",
        "K-theory",
        "Mechatronics",
        "Digital humanities",
        "Oomoto",
        "Applied sociology",
        "Ancient",
        "Sociology of finance",
        "American history",
        "Socialist economics",
        "Database",
        "Podiatry",
        "Special operations",
        "Chondogyo",
        "Xenobiology",
        "Medicinal chemistry",
        "Feminist economics",
        "Screenwriting",
        "Molecular physics",
        "Affective science",
        "Semiotics",
        "Trench warfare",
        "Neuroscience",
        "Psychosomatic",
        "Computer programming",
        "Cosmetology",
        "Australian studies",
        "Continental philosophy",
        "Social economy",
        "Philosophy of language",
        "English literature",
        "War",
        "Cuisine",
        "Sociology of the body",
        "Doctrine",
        "Food porn",
        "Gender theory",
        "Sociology of globalization",
        "Technological history",
        "Acting",
        "Strategic geography",
        "Empirical sociology",
        "Theology",
        "Meteorology",
        "Environmental chemistry",
        "Immunology",
        "Wireless computing",
        "Computer engineering",
        "Mathematical system theory",
        "Civil law",
        "Agnosticism",
        "Food choice",
        "Sociology of technology",
        "Sociology of social movements",
        "Natural product chemistry",
        "Theoretical sociology",
        "Biological anthropology",
        "Mathematical physics",
        "Logic programming",
        "Mock combat",
        "Historic preservation",
        "Elementary particle physics",
        "Educational leadership",
        "Computational sociology",
        "Collective behavior",
        "Sociology of generations",
        "Arms control",
        "Geomorphology",
        "Forensic anthropology",
        "Sports medicine",
        "Managerial economics",
        "Plant science",
        "Psychiatry",
        "Supply chain management",
        "Classics",
        "Asymmetric warfare",
        "Sociology of art",
        "Systematics",
        "Block design and analysis of variance",
        "Synthetic chemistry",
        "Public relations",
        "Social theory",
        "Accounting",
        "Military exercises",
        "Public policy by country",
        "Social dynamics",
        "Athletic director",
        "Sports coaching",
        "Piano",
        "Deception",
        "Biblical hebrew",
        "Distributed database",
        "Secondary education",
        "Physical therapy",
        "Astrophysics",
        "Labor history",
        "Ancient egyptian religion",
        "Humanistic psychology",
        "Clinical microbiology",
        "Integral geometry",
        "Organizational communication",
        "Clinical immunology",
        "Egyptology",
        "Affine geometry",
        "Industrial design",
        "Pediatric psychology",
        "Graph theory",
        "Mathematical optimization",
        "Socioeconomics",
        "Music genre",
        "Non-fiction writing",
        "Human geography",
        "Mobile computing",
        "Decorative arts",
        "Community organizing",
        "Emergency management",
        "Simulation",
        "Molecular biology",
        "Sustainability studies",
        "Behavioural genetics",
        "Film",
        "Internet",
        "Vedic study",
        "Ocean engineering",
        "Molecular pathology",
        "Computational finance",
        "Command and control",
        "Oceanography",
        "Robotics",
        "Inorganic chemistry",
        "Numerical analysis",
        "Experimental psychology",
        "History of literature",
        "Heterosexism",
        "Animal communication",
        "Sustainable development",
        "Mysticism",
        "Human anatomy",
        "Sociology of gender",
        "Mythology",
        "Directing",
        "Housing",
        "Paleoanthropology",
        "Mathematical psychology",
        "Social phenomenon",
        "Physical activity",
        "Physiology",
        "Acoustics",
        "Nonverbal communication",
        "Information architecture",
        "Non-standard analysis",
        "Entomology",
        "Mass transfer",
        "Real analysis",
        "Mechanochemistry",
        "Eastern philosophy",
        "Computational geometry",
        "Computability theory",
        "Children's geographies",
        "Dance",
        "Military operation",
        "Electrochemistry",
        "Stem cell research policy",
        "Multi-valued logic",
        "Analytical chemistry",
        "Enterprise systems engineering",
        "Symbolic interactionism",
        "World literature",
        "Thermodynamics",
        "Near eastern archaeology",
        "Normative ethics",
        "Chinese folk religion",
        "Clandestine operation",
        "Medieval literature",
        "Jazz studies",
        "Arithmetic combinatorics",
        "Naval science",
        "Central asian studies",
        "Culturology",
        "Conflict theory",
        "Cavalry",
        "Special education",
        "Knowledge management",
        "Land management",
        "Family psychology",
        "Family systems theory",
        "Ecological engineering",
        "Radio",
        "Biochemical engineering",
        "Program semantics",
        "Mass communication",
        "Occupational therapy",
        "Church music",
        "Process design",
        "Behavioral sociology",
        "Marine engineering",
        "Counselor education",
        "Zoosemiotics",
        "Public international law",
        "Siege",
        "Hematology",
        "Computational number theory",
        "Primary care",
        "Engineering geology",
        "Biochemical systems theory",
        "Graphic design",
        "Demography/population",
        "Project management",
        "Comparative psychology",
        "Educational philosophy",
        "Comparative law",
        "Medieval philosophy",
        "Military law",
        "Grammar",
        "Social conflict theory",
        "Gemology",
        "Social constructionism",
        "Mathematical economics",
        "Cultural geography",
        "Structural engineering",
        "Fisheries management",
        "Computational linguistics",
        "Neuroethology",
        "Accompanying",
        "Field ministry",
        "Policy sociology",
        "Inventory theory",
        "Analytic philosophy",
        "Metaphysics",
        "Meta-ethics",
        "Organ and historical keyboards",
        "Latin american history",
        "Futures studies",
        "Irregular warfare",
        "Developmental biology",
        "Cloud computing",
        "African history",
        "Music education",
        "Rehabilitation psychology",
        "Undercover",
        "Automotive engineering",
        "Chemical",
        "Food policy",
        "Wildlife observation",
        "Performance poetry",
        "Historical geography",
        "Broadcast journalism",
        "Game theory",
        "Nanotechnology",
        "Educational sociology",
        "Phenomenological sociology",
        "Environmental psychology",
        "Functional programming",
        "Computer architecture",
        "Synthetic biology",
        "Disaster response",
        "Cover",
        "Labor economics",
        "Physical fitness",
        "Epidemiology",
        "Social geography",
        "Political philosophy",
        "Outdoor education",
        "Political economy",
        "Sindhology",
        "Industrial and labor relations",
        "Appalachian studies",
        "Canadian studies",
        "Electronic media",
        "Tactical objective",
        "Covert operation",
        "History of dance",
        "Sociology of natural resources",
        "Moral theology",
        "Business ethics",
        "Energy policy",
        "Hoax",
        "Geochemistry",
        "Surgical strike",
        "Sociology of markets",
        "Cosmochemistry",
        "Sociology of fatherhood",
        "Decision analysis",
        "Sociology of law",
        "Population geography",
        "Systems philosophy",
        "Bibliometrics",
        "Maritime archaeology",
        "Oral and maxillofacial surgery",
        "Philosophy of social science",
        "Periodontics",
        "Civil service",
        "Nationalism studies",
        "Biological psychology",
        "Theoretical physics",
        "Literary journalism",
        "Food safety",
        "Comparative religion",
        "Entrepreneurship",
        "Toxicology",
        "Ancient greek history",
        "Doxastic logic",
        "Men's studies",
        "Philosophy of music",
        "Military sociology",
        "Linear algebra",
        "Ornithology",
        "Occupational psychology",
        "Christian theology",
        "Cyberwarfare",
        "Latin",
        "Quantum gravity",
        "Nanoengineering",
        "Defense industry",
        "Applied economics",
        "Physics education",
        "New cybernetics",
        "Monetary policy",
        "Biomechanical engineering",
        "Speleology",
        "Multimedia, hypermedia",
        "Textile design",
        "Dance notation",
        "Psychological",
        "Computational physics",
        "Performance science",
        "Pest control",
        "Lattice theory",
        "Cultural policy",
        "Statistical theory",
        "English studies",
        "Public policy doctrine",
        "Quantum chemistry",
        "Lexicology",
        "Abnormal psychology",
        "Human development theory",
        "Economic sector",
        "Paleontology",
        "Military sports",
        "Sociology of conflict",
        "Military intelligence",
        "Guerrilla warfare",
        "Land",
        "I-kuan tao",
        "Pedology",
        "Education policy",
        "Speech communication",
        "Sampling theory",
        "Etymology",
        "Ancient roman history",
        "Oncology",
        "Conceptual systems",
        "Occupational health psychology",
        "Poetics",
        "Science and technology studies",
        "Resource economics",
        "Mineralogy",
        "Woodcraft",
        "Bioeconomics",
        "Accounting scholarship",
        "Clinical neuropsychology",
        "Poetry",
        "World history",
        "Museology",
        "Monetary economics",
        "Assignment problem",
        "Japanology",
        "Hydrodynamics",
        "Mesosociology",
        "Economic value",
        "Projective geometry",
        "Developmental psychology",
        "Biomechanics",
        "Forensic developmental psychology",
        "Clinical psychology",
        "Computational mathematics",
        "Computer science",
        "World-systems theory",
        "Health psychology",
        "Evolutionary biology",
        "Intermodal transportation studies",
        "Civics",
        "Pakistan studies",
        "Real options analysis",
        "Bilingual education",
        "Field theory",
        "Malacology",
        "Arcade game",
        "Interior architecture",
        "Landscape design",
        "Climatology",
        "Probability",
        "Human physiology",
        "Christian ethics",
        "Electromagnetism",
        "Scientific computing",
        "Fashion design",
        "Microwave astronomy",
        "Science studies",
        "Mycology",
        "Neuropsychology",
        "Mechanics",
        "Sociology of the internet",
        "Aerobics",
        "Architectural analytics",
        "Fuzzy logic",
        "Nuclear engineering",
        "Sociology of cyberspace",
        "Biotechnology",
        "Supranational law",
        "Agrochemistry",
        "Purchasing",
        "Semantics",
        "Complex systems",
        "Biostatistics",
        "Philosophical logic",
        "Sociology of culture",
        "Cosmology",
        "Regression",
        "Behavioural economics",
        "Bushcraft",
        "Fractal geometry",
        "Indian history",
        "Mental health",
        "Health informatics",
        "Systematic theology",
        "Traditional medicine",
        "Engineers",
        "Information technology",
        "War crimes",
        "Calculus",
        "Coastal management",
        "Histology",
        "Economic history",
        "Materiel",
        "Industrial organization",
        "Geography",
        "Personal fitness training",
        "Radiochemistry",
        "Criminal justice",
        "Parasitology",
        "Organic chemistry",
        "Musical composition",
        "Obstetrics",
        "Galaxy formation and evolution",
        "Mythology and folklore",
        "Composition studies",
        "Optimal maintenance",
        "Psychoanalytic sociology",
        "Mathematical sociology",
        "Sociology of peace, war, and social conflict",
        "Optical astronomy",
        "Complexity economics",
        "Interior design",
        "Escapology",
        "Representation theory",
        "Immigration policy",
        "Sociology of the history of science",
        "Historical theology",
        "Choral conducting",
        "Welfare economics",
        "Sleep medicine",
        "Cryptography",
        "Ethnomethodology",
        "Conducting",
        "New religious movements",
        "Sample survey",
        "Visual sociology",
        "Tort law",
        "Participatory economics",
        "Recording",
        "Interstellar medium",
        "New testament greek",
        "Chronobiology",
        "Pre-columbian era",
        "Leadership",
        "Conventional",
        "East asian studies",
        "Social stratification",
        "Physical chemistry",
        "Distributed algorithms",
        "Stochastic process",
        "Stellar nucleosynthesis",
        "Biological systems engineering",
        "Systems theory",
        "Deontic logic",
        "Forensic science",
        "Concurrency theory",
        "Counter-attack",
        "Pharmacology",
        "Stochastic processes",
        "Edaphology",
        "Naval tactics",
        "Bioengineering",
        "Neurochemistry",
        "Transpersonal psychology",
        "Theoretical chemistry",
        "Sport management",
        "Hinduism",
        "Economic sociology",
        "Translation",
        "Proof theory",
        "Geometric topology",
        "Aerospace engineering",
        "Societal of autism",
        "Infiltration",
        "Korean studies",
        "Quantum physics",
        "Cell biology",
        "Organizational studies",
        "Fourier analysis",
        "Organization theory",
        "Confucianism",
        "Sociology of social change",
        "Human behavioral ecology",
        "Electrical engineering",
        "Mathematical chemistry",
        "Animation",
        "Intelligence agency",
        "Economic",
        "Statistical mechanics",
        "Analytic number theory",
        "Applied ethics",
        "Contemporary philosophy",
        "Experimental physics",
        "Physical education",
        "Sociology of human consciousness",
        "Philosophy of mathematics",
        "Automata theory",
        "Behavioural science",
        "Algebraic number theory",
        "Fourth-generation warfare",
        "Nonprofit administration",
        "Recursion theory",
        "Process engineering",
        "Surgery",
        "Compilers",
        "Electronic engineering",
        "Sociology of work",
        "Australian history",
        "Ethnomusicology",
        "Sociology of childhood",
        "User experience design",
        "Reaction engineering",
        "Musicology",
        "Primatology",
        "Computer vision",
        "Relational database",
        "Computational statistics",
        "Semiconductors",
        "History",
        "Tax policy",
        "Planetary science",
        "Control systems engineering",
        "Gastroenterology",
        "Conservation psychology",
        "Algebraic topology",
        "Algebraic geometry",
        "Approximation theory",
        "Canadian politics",
        "Legal management",
        "Forensic psychology",
        "Law and economics",
        "Sociology of science",
        "Astrobiology",
        "Structural biology",
        "Type design",
        "European history",
        "Post-modern literature",
        "Survey methodology",
        "Type theory",
        "Environmental engineering",
        "Asian psychology",
        "Ecology",
        "Visual communication",
        "Feminist philosophy",
        "Hermeneutics",
        "Imperative programming",
        "Operator theory",
        "Social development",
        "Reliability theory",
        "Positive psychology",
        "Photochemistry",
        "Architectural sociology",
        "Psychology",
        "Econometrics",
        "Scoutcraft",
        "Modern history",
        "Bariatric surgery",
        "Legal psychology",
        "Computational complexity theory",
        "Chemistry education",
        "Social research",
        "Structural mechanics",
        "Atomic physics",
        "Polymer science",
        "Sociology of disaster",
        "Philosophy of law",
        "Environmental history",
        "Business law",
        "Public administration",
        "Horticulture",
        "Choreography",
        "Propaganda",
        "Theft",
        "Industry",
        "Biophysics",
        "Surface chemistry",
        "Systems engineering",
        "Conservation biology",
        "Virology",
        "Natural resource sociology",
        "Critical theory",
        "Community psychology",
        "Organology",
        "Dogmatic theology",
        "Medical psychology",
        "Common law",
        "Alternative education",
        "Strategic studies",
        "Comparative literature",
        "Speech and language pathology",
        "Programming language semantics",
        "Fire ecology",
        "Cartography",
        "Peace and conflict studies",
        "Helioseismology",
        "Consumer education",
        "Aesthetics",
        "Business english",
        "Diachronic linguistics",
        "Ancient history",
        "Pomology",
        "Sociology of literature",
        "Indonesian history",
        "Fiscal policy",
        "Dramaturgical sociology",
        "Concurrent programming",
        "Biomaterials",
        "Folklore",
        "Measure theory",
        "Phytochemistry",
        "Fault-tolerant computing",
        "Otolaryngology",
        "High-performance computing",
        "Non-governmental organization (ngo) administration",
        "Financial econometrics",
        "Ecological systems theory",
        "Plastic surgery",
        "Foodservice management",
        "Corporate law",
        "Vlsi design",
        "Condensed matter physics",
        "Wind ensemble conducting",
        "Systems immunology",
        "Therapy",
        "Discrete geometry",
        "Iranian studies",
        "Knowledge economy",
        "Continuum mechanics",
        "Phycology",
        "Sociology of film",
        "Technology policy",
        "Gourmet",
        "Model theory",
        "Medical anthropology",
        "Industrial",
        "Islamic law",
        "Catalysis",
        "Animal law",
        "Popular culture studies",
        "Pastoral counseling",
        "Counter-intelligence",
        "International law",
        "Quality control",
        "Cleaning",
        "Mathematics education",
        "Interpretive sociology",
        "Media psychology",
        "Digital media",
        "Counter-offensive",
        "Moral psychology and descriptive ethics",
        "Ethics",
        "German studies",
        "Agricultural education",
        "Principles of war",
        "Early modern",
        "Information science",
        "Higher education",
        "Gnosticism",
        "Social philosophy",
        "Environmental sociology",
        "Systems science",
        "Cultural anthropology",
        "Marxian economics",
        "Nuclear energy policy",
        "Navigation",
        "Seafaring",
        "Information system",
        "Agronomy",
        "Theism and atheism",
        "Church history",
        "Dental surgery",
        "Social anthropology",
        "Discourse analysis",
        "Television studies",
        "Communication design",
        "Museum administration",
        "History of linguistics",
        "Natural language processing",
        "Feminine psychology",
        "Tenrikyo",
        "Sociobiology",
        "Security",
        "Operations management",
        "Criminal procedure",
        "Algorithms",
        "Landscape ecology",
        "Espionage",
        "Indology",
        "Public finance",
        "Psephology",
        "Scientific visualization",
        "Shinto",
        "Palaeogeography",
        "Canon law",
        "Information",
        "Quantum computing",
        "Cognitive science",
        "Genetics",
        "Cybernetics",
        "Housing policy",
        "Technical writing",
        "Sociolinguistics",
        "Paleobiology",
        "Orchestral studies",
        "Formal languages",
        "Interaction design",
        "Sculpture",
        "Native american religions",
        "Programming paradigms",
        "Admiralty law",
        "Computational neuroscience",
        "Pharmaceutical policy",
        "Libertarianism",
        "Consumer psychology",
        "Control theory",
        "Medical toxicology",
        "Jealousy sociology",
        "Tectonics",
        "Microbiology",
        "Outline of video games",
        "Urban studies or urban sociology/rural sociology",
        "Architecture",
        "Ecological psychology",
        "Sociology of development",
        "School social work",
        "Sociology of scientific knowledge",
        "Data management",
        "Daoism",
        "Ethnochoreology",
        "Gender studies",
        "Music psychology",
        "Human ecology",
        "Energy economics",
        "Civil defense",
        "Emergency medicine",
        "Language education",
        "Pathology",
        "Ichthyology",
        "Culinary tourism",
        "Quantum mechanics",
        "Molecular engineering",
        "Playwrighting",
        "Food pairing",
        "Acoustical engineering",
        "Materials engineering",
        "User interface design",
        "Aerial",
        "Medical cybernetics",
        "Herpetology",
        "Environmental geography",
        "Cryobiology",
        "Ethnohistory",
        "Anatomy",
        "Information economics",
        "Theory of computation",
        "Decision theory",
        "Prehistoric",
        "Usage",
        "Sociology of religion",
        "Magazine",
        "Paralegal studies",
        "Total war",
        "Business informatics",
        "Multivariate analysis",
        "Anarchist economics",
        "Parapsychology",
        "Geometry",
        "Ceramic engineering",
        "Recreation therapy",
        "Agricultural engineering",
        "Security policy",
        "Steganography",
        "Battle",
        "Psychobiology",
        "Human evolution",
        "Photonics",
        "Industrial policy",
        "Aeronautics",
        "Disarmament",
        "Port management",
        "Prehistoric archaeology",
        "Political geography & geopolitics",
        "Logic",
        "Evolutionary sociology",
        "Philosophy of education",
        "Foxhole",
        "Linguistic typology",
        "Myrmecology",
        "African religions",
        "Bioinformatics",
        "Finite geometry",
        "Ethnozoology",
        "Food science",
        "Human resources management",
        "International economics",
        "International affairs",
        "Public economics",
        "Zoroastrianism",
        "Ethnic studies",
        "Curriculum and instruction",
        "Sociology of aging",
        "Object-oriented programming",
        "Fire safety",
        "Systems ecology",
        "Structural sociology",
        "Veterinary medicine",
        "Mammalogy",
        "Data mining",
        "Phonetics",
        "Agroecology",
        "Urban geography",
        "Zoology",
        "Arachnology",
        "Comparative anatomy",
        "Southeast asian studies",
        "Military education",
        "Historical linguistics",
        "Viticulture",
        "Kinesiology",
        "Hematopathology",
        "Competition law",
        "Evolutionary psychology",
        "Heat transfer",
        "Old church slavonic",
        "Psycholinguistics",
        "Development geography",
        "Software engineering",
        "Radio astronomy",
        "Sedimentology",
        "Goal",
        "Media studies",
        "Philosophy of mind",
        "Orthoptics",
        "Philosophy of perception",
        "Philosophy of chemistry",
        "Decision science",
        "Glaciology",
        "Physical metallurgy",
        "Slavic studies",
        "Neurology",
        "Cryptanalysis",
        "Naval architecture",
        "Psychometrics",
        "Social choice theory",
        "Naval",
        "Control engineering",
        "Vehicle engineering",
        "Beekeeping",
        "Political psychology",
        "Social psychology",
        "Sumerian religion",
        "Cognitive psychology",
        "Slot machine",
        "Sikhism",
        "Cheminformatics",
        "Appetite",
        "Image processing",
        "Digital journalism",
        "Staff",
        "Armor",
        "Civil engineering",
        "Stellar astrophysics",
        "Orchestral conducting",
        "Clinical biochemistry",
        "Flavor",
        "Personal trainer",
        "Astronomy",
        "Object database",
        "Optics",
        "British literature",
        "Nontheism",
        "Specialty foods",
        "Sociology of the family",
        "International organizations",
        "Special forces",
        "Psychopathology",
        "Delicacy",
        "Optical physics",
        "Respiratory medicine",
        "Business analysis",
        "Industrial engineering",
        "Randomized algorithms",
        "Anarchism",
        "Sociology of motherhood",
        "Natural resource management",
        "Star formation",
        "Liturgy",
        "Lti system theory",
        "Esotericism",
        "Community practice",
        "Systems theory in anthropology",
        "Scholasticism",
        "Cytology",
        "Counseling psychology",
        "Filmmaking",
        "Sociology of race and ethnic relations",
        "Science policy",
        "Jewish law",
        "Film criticism",
        "Neurosurgery",
        "Preventive medicine",
        "Economic systems",
        "Peace education",
        "Travel psychology",
        "Philosophy of physics",
        "Education and training",
        "Pragmatics",
        "Silviculture",
        "Category theory",
        "Technology education",
        "Newspaper",
        "Andrology",
        "Black holes",
        "Modal logic",
        "Order theory",
        "Mathematical logic",
        "Health informatics/clinical informatics",
        "Topos theory",
        "Rhetoric",
        "Critical management studies",
        "Property law",
        "Vaccination policy",
        "Music theory",
        "Modern philosophy",
        "Noncommutative geometry",
        "Formal methods",
        "Electronic",
        "Stage design",
        "Drug policy",
        "Gynaecology",
        "Standard english",
        "Vehicles",
        "Sacred music",
        "Journalism",
        "Human–computer interaction",
        "Health geography",
        "Meta-philosophy",
        "Geotechnical engineering",
        "Formal verification",
        "Warrior",
        "Governmental affairs",
        "Mechanical engineering",
        "Ethnobotany",
        "Singing",
        "Quantitative psychology",
        "Humanistic informatics",
        "Middle east studies",
        "Public service",
        "Sociomusicology",
        "Petrology",
        "Apiology",
        "Languages",
        "Mercenary",
        "Anthropological linguistics",
        "Management",
        "Dynamical systems",
        "Administrative law",
        "Marxist sociology",
        "Implantology",
        "Scenography",
        "Leisure studies",
        "Aftertaste",
        "Business economics",
        "Purification",
        "Ethnology",
        "Financial economics",
        "American literature",
        "Black psychology",
        "Commutative algebra",
        "Latin american studies",
        "Infrared astronomy",
        "Food presentation",
        "Automated reasoning",
        "Molecular genetics",
        "Mass transit",
        "Cetology",
        "Marketing",
        "Dermatopathology",
        "History of computer science",
        "Macrosociology",
        "Highway safety",
        "Psychophysics",
        "Coastal geography",
        "Ancient philosophy",
        "Chinese history",
        "Mining engineering",
        "Molecular mechanics",
        "Jewish studies",
        "Military medicine",
        "Haemostasiology",
        "Astrochemistry",
        "Information retrieval",
        "Convex geometry",
        "Finance",
        "Occult",
        "Sport psychology",
        "Science education",
        "Religious education",
        "Charge",
        "Sociological theory",
        "Marxism",
        "Scientific history",
        "Soil science",
        "Rehabilitation medicine",
        "Sociology of deviance",
        "Analytical sociology",
        "Clinical pathology",
        "Russian and eastern european studies",
        "Political history",
        "Traumatology",
        "Development economics",
        "Dietetics",
        "Nematology",
        "Applied physics",
        "Polymer engineering",
        "Machine learning",
        "Black studies",
        "Forensic pathology",
        "Mathematical statistics",
        "X-ray astronomy",
        "Sports journalism",
        "Histopathology",
        "Attrition",
        "Missiology",
        "Prosthodontics",
        "Forensic entomology",
        "Craft",
        "Evolutionary economics",
        "Paramilitary",
        "Economic geography",
        "Critical sociology",
        "Public sociology",
        "Parallel computing",
        "Military history",
        "Engineering cybernetics",
        "Regional geography",
        "Word usage",
        "Computer communications",
        "Vehicle dynamics",
        "Sports biomechanics",
        "Transportation engineering",
        "Military engineering",
        "Disaster research",
        "Manufacturing engineering",
        "African studies",
        "Industrial sociology",
        "Business",
        "Computer-aided engineering",
        "Domestic policy",
        "Environmental science",
        "Personality psychology",
        "Environmental economics",
        "Polish sociology",
        "Informatics",
        "Statistical modelling",
        "Immunochemistry",
        "Comparative politics",
        "Islamic studies",
        "Traffic psychology",
        "Real estate economics",
        "Queer studies",
        "Literary genre",
        "Algebra",
        "Biomedical engineering",
        "Homiletics",
        "Enology",
        "Educational technology",
        "Social transformation",
        "Sociology of terrorism",
        "Non-euclidean geometry",
        "Sociology of knowledge",
        "Health policy",
        "Geography and outline of geography",
        "Post-colonial literature",
        "Dramaturgy",
        "Hepatology",
        "Petroleum engineering",
        "Historical sociology",
        "Ergonomics",
        "Surveying",
        "History of computer hardware",
        "Endodontics",
        "Fluid mechanics",
        "Microsociology",
        "Tax law",
        "String theory",
        "Network science",
        "Hydrology/hydrography",
        "Space policy",
        "Child psychopathology",
        "Infantry",
        "Diet",
        "Sacramental theology",
        "Biocybernetics",
        "Cytogenetics",
        "Sportscasting",
        "Puppetry",
        "Police science",
        "Investment policy",
        "Philosophy of science",
        "Film theory",
        "Landscape architecture",
        "Modern",
        "Group psychology",
        "Aerobiology",
        "Construction",
        "Urban planning",
        "Counter-insurgency",
        "Buddhist studies",
        "Political behavior",
        "Environmental management",
        "Reasoning errors",
        "Battlespace",
        "Computational economics",
        "Digital culture",
        "Computational systems biology",
        "Intuitionistic logic",
        "Combat",
        "Systems biology",
        "Film studies",
        "Optometry",
        "Coastal engineering",
        "Sociology of language",
        "Limited war",
        "Athletic training",
        "Musical theatre",
        "Atheism",
        "Cyber",
        "Ring theory",
        "Behavioral geography",
        "Volcanology",
        "Platonism",
        "Philosophy of religion",
        "Systemic therapy",
        "Response surface methodology",
        "Set theory",
        "Islamic economics",
        "Social policy",
        "International trade",
        "Taxonomy",
        "Determinism and free will",
        "Fine arts",
        "Medical sociology",
        "Social network analysis",
        "Paleoecology",
        "Literary theory",
        "Air",
        "Anthropological criminology",
        "Military policy",
        "Activism",
        "Feminist sociology",
        "Infographics",
        "Critical pedagogy",
        "Histochemistry",
        "Hydrogenation",
        "Marine transportation",
        "Russian history",
        "Artillery",
        "Philosophy of action",
        "Philosophy of history",
        "Psychotherapy",
        "Public policy school",
        "Conspiracy theory",
        "Cardiothoracic surgery",
        "Cross-cultural studies",
        "Theatre",
        "Social control",
        "Human sexuality",
        "Sociology of government",
        "Amphibious warfare",
        "Expert systems",
        "Ecological economics",
        "Palatability",
        "Growth economics",
        "Physical geography",
        "High-energy astrophysics",
        "Sociocybernetics",
        "Information systems",
      ]

      @programs = [
        "EGL",
        "FreeDOS",
        "DrRacket",
        "OpenCL",
        "Objective-C",
        "Curl",
        "J++",
        "EiffelStudio",
        "MOS",
        "Netbeans",
        "Haskell",
        "AMOS",
        "PHPEclipse",
        "Stada",
        "Trac",
        "Vi",
        "Zsh",
        "Delphi",
        "TeXShop",
        "C#",
        "OpenSolaris",
        "Emacs",
        "Haxe",
        "Logo",
        "Assembly Language",
        "PEARL",
        "nvi",
        "QtScript",
        "GLD",
        "Remix OS",
        "Notepad++",
        "AppCode",
        "Visual J#",
        "C Shell",
        "COBOL",
        "Visual J++",
        "Gedit",
        "Swift",
        "Perl 6",
        "ECMAScript",
        "JDeveloper",
        "BPEL",
        "Objective-J",
        "Mousepad",
        "AutoLisp",
        "LiveCode",
        "F#",
        "ZetaLisp",
        "NeXTSTEP",
        "Racket",
        "illumos",
        "AIX",
        "OS/360",
        "Emacs Lisp",
        "TextEdit",
        "Vim",
        "JBuilder",
        "TextPad",
        "Microsoft Visual Studio",
        "XPL",
        "Microcode",
        "Geany",
        "Gnome",
        "Neko",
        "Plan 9 from Bell Labs",
        "Atari DOS",
        "Bash",
        "Clojure",
        "NoteTAb",
        "Cg",
        "PyCharm",
        "RISC OS",
        "Unix",
        "Unix shell",
        "D",
        "GPL",
        "Caml",
        "RDOS",
        "Visual LISP",
        "Sublime Text",
        "CodeLite",
        "Machine code",
        "NetWare",
        "C*",
        "Pascal",
        "IntelliJ",
        "JCreator",
        "XSharp",
        "Julia",
        "OpenBSD",
        "Tcl",
        "DOS/360",
        "Dreamweaver",
        "HLSL",
        "Picolisp",
        "Xenix",
        "TXL",
        "Dev-Pascal",
        "Erlang",
        "CP/M",
        "Komodo IDE",
        "CP/CMS",
        "IDLE",
        "Lua",
        "Solaris",
        "X10",
        "Pico",
        "Code::Blocks",
        "R++",
        "Object Lisp",
        "RStudio",
        "AOS",
        "Notepad",
        "LaTeX",
        "OS/2 Warp",
        "JScript",
        "GNU",
        "BSD",
        "C",
        "NetBSD",
        "Notepad2",
        "Perl",
        "Go",
        "Word",
        "RPG",
        "Microsoft Small Basic",
        "Windows",
        "YAML",
        "F",
        "Rust",
        "NPL",
        "Mesa",
        "Nodeclipse",
        "VS/9",
        "Zeno",
        "Amiga E",
        "FreeBASIC",
        "Apple DOX",
        "Oak",
        "UnixWare",
        "Wolfram Language",
        "CMS-2",
        "HDOS",
        "Komodo Edit",
        "Visual Studio",
        "ALGOL",
        "Xcode",
        "Qt Creator",
        "DOS",
        "A#",
        "XBase++",
        "Free Pascal IDE",
        "X++",
        "SML",
        "BCPL",
        "SymbOS",
        "ColdFusion",
        "Java",
        "dBasic",
        "C--",
        "APL",
        "Ada",
        "Simula",
        "TextMate",
        "MATLAB",
        "PhpED Professional",
        "Midori",
        "KWrite",
        "Nano",
        "MUMPS",
        "OSv",
        "ProDOX",
        "Amiga Unix",
        "LPC",
        "MonoDevelop",
        "J",
        "Mathematica",
        "MicroEMACS",
        "SQL",
        "BeOS",
        "Ruby",
        "SLIME",
        "EXEC II",
        "OBJ2",
        "KDE",
        "Ghost OS",
        "XBase",
        "CoffeeScript",
        "Android",
        "Windows CE",
        "MDL",
        "PyScripter",
        "Javascript",
        "AMSDOS",
        "EXEC I",
        "Goobuntu",
        "LynxOS",
        "LibreOffice",
        "Excel",
        "Leafpad",
        "Chromium OS",
        "Smalltalk",
        "Zorin OS",
        "PocketStudio",
        "PHPEdit",
        "Apple Pascal",
        "KDevelop",
        "iOS",
        "Visual Fortran",
        "OCaml",
        "Eclipse",
        "GDScript",
        "MyEclipse",
        "NetBeans",
        "X11 Xedit",
        "FORTRAN",
        "Darwin",
        "Nim",
        "Codeanywhere",
        "Legoscript",
        "Mac OS",
        "Lisp",
        "OS/2",
        "LotusScript",
        "MS-DOS",
        "Linux",
        "TeX",
        "ed",
        "SlickEdit",
        "XEDIT",
        "TypeScript",
        "Inform",
        "CDOS",
        "Object Pascal",
        "PLEX",
        "RubyMine",
        "Ceylon",
        "MicroScript",
        "Z80-RIO",
        "XTS-400",
        "ARX",
        "CPL",
        "Krita",
        "MIPS",
        "Ubuntu",
        "R",
        "Visual Basic",
        "Windows NT",
        "ReactOS",
        "Kotlin",
        "CLion",
        "PikeOS",
        "SCO Unix",
        "Visual FoxPro",
        "Vim script",
        "C++",
        "Python",
        "BASIC",
        "LISA",
        "eC",
        "XPath",
        "OS/8",
        "Atom",
        "LispWorks",
        "JavaFX Script",
        "AmigaOS",
        "PHP",
        "J#",
        "WebAssembly",
        "Visual Basic .NET",
        "Apple SOS",
        "jEdit",
        "Visual Studio Code",
        "BBEdit",
        "Octave",
        "Dart",
      ]

      def Bulk.sports
        @sport
      end


      def Bulk.software
        @programs
      end


      def Bulk.studies
        @study
      end
    end
  end
end
